### ISSUE TITLE
World not Loading In Modpack RR3

### ISSUE THREAD

**Issue by Periam** [fewizz/NotEnoughIDs#10]
Fewizz..
I installed the mod on RR3 and the first time the world was loaded, there are some chunk that are missing (breaking a block made them appear back). I close and save the world and went trying to re-loaded all the chucnk are missing.

**Comment by Solarstrike** [comment]
Try the test builds.

**Comment by fewizz** [comment]
You have NEIDTweaker?

**Comment by Periam** [comment]
Sorry it take me a while. I have the lasted Fastcraft version and was not good I am still having the same problems, chunk that do not load, and if I return to the world all is gone-
- Fewizz I do not have NEIDTweaker (and could not find it on the web), from RR3 modpack I just added your mod. the rest is the original pack

**Comment by fewizz** [comment]
http://minecraft.curseforge.com/mc-mods/235107-notenoughids/files/2253083

**Comment by Periam** [comment]
Guys
Thanks a lot after installed the NEIDTweaker the problem of chunk was resolved.
Do you know why Mapwriter is not working properly?

**Comment by Solarstrike** [comment]
Check to see if you enabled underground mode.

**Comment by Periam** [comment]
In game turning on and off Underground mode is like they are inverted. 
when the map should be showing the overworld it shows the underground

**Comment by Solarstrike** [comment]
Try reporting this to ProfMobius or the Resonant Rise team.
Either that, or switch map mods (I'd recommend JourneyMap)

**Comment by Adaptivity** [comment]
I can confirm that Mapwriter 2 map rendered as black circle. It can be either Mapwriter or NEID issue. I've filled a new ticket here: #11
