### ISSUE TITLE
Mapwriter's minimap render broken

### ISSUE THREAD

**Issue by Adaptivity** [fewizz/NotEnoughIDs#11]
@fewizz code is here: https://github.com/Vectron/mapwriter

**Comment by Vectron** [comment]
what would be the best place to get the max blockid that you changed without being dependant on your mod?

i still have a hardcoded reference in the mod to 4096 for max blocks that i use to build some arrays.

**Comment by fewizz** [comment]
I'm changing final var "MAX_BLOCK_ID" in GameData class(in fml). [P.S.] (https://github.com/fewizz/mapwriter/releases)

**Comment by Vectron** [comment]
unfortunatly that field is private.

as for the changes if i understand it right it will break if your mod is not installed right? (not counting the refference to your mod)

**Comment by fewizz** [comment]
yep...
