### ISSUE TITLE
incomplete worldgen

### ISSUE THREAD

**Issue by VasyaOrk** [fewizz/NotEnoughIDs#14]
without NotEnoughIDs normal world generation and loading 
![2015-09-02_21 16 18](https://cloud.githubusercontent.com/assets/11337638/9640081/5ee41b4c-51b8-11e5-94e6-f520a667d305.png)
![2015-09-02_21 16 27](https://cloud.githubusercontent.com/assets/11337638/9640084/6061422e-51b8-11e5-917f-3adf04791675.png)

server : KCauldron-1.7.10-1492.155-server
client : Forge10.13.4.1492-1.7.10

mod list

Baubles-1.7.10-1.0.1.10.jar
CodeChickenLib-1.7.10-1.1.3.138-universal.jar
Eureka-1.7.10-3.0.2.jar
ForgeMultipart-1.7.10-1.2.0.345-universal.jar
ForgeRelocation-0.0.1.4-universal.jar
ForgeRelocationFMP-0.0.1.2-universal.jar
MrTJPCore-1.1.0.31-universal.jar

1.7.10_AM2-1.4.0.008.jar
ABO-MC1.7.10-BC7-release3.0.1.jar
additionalpipes-4.6.0.jar
AE2BD_ae2stuff-0.4.3.47-mc1.7.10.jar
AE2_appliedenergistics2-rv2-stable-10.jar
AE2_ExtraCells-1.7.10-2.2.73b129.jar
AE2_IntelligentEnergistics-1.7.10-2.1.4.554-universal.jar
AnimationAPI-1.7.10-1.2.4.jar
AOBD-2.7.1.jar
ATG-1.7.10-0.12.0.jar
Automagy-1.7.10-0.26.3.jar
backpack-2.0.1-1.7.x.jar
BD_bdlib-1.9.1.97-mc1.7.10.jar
BD_gendustry-1.5.2.107-mc1.7.10.jar
BD_generators-0.9.17.102-mc1.7.10.jar
BD_neiaddons-1.12.11.36-mc1.7.10.jar
BD_pressure-1.2.3.117-mc1.7.10.jar
BetterStorage-1.7.10-0.12.0.124.jar
BiblioCraft[v1.10.6][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BiblioWoods[Forestry][v1.7].jar
BiblioWoods[Highlands][v1.4].jar
BiblioWoods[Natura][v1.5].jar
BigReactors-0.4.2A2.jar
BigTrees-172b-forge1060.jar
binnie-mods-2.0-pre14.jar
BiomesOPlenty-1.7.10-2.1.0.1387-universal.jar
BloodArsenal-1.7.10-1.1-14.jar
BloodMagic-1.7.10-1.3.3-5.jar
BloodUtils-1.4_B0.jar
BluePower-1.7.10-0.2.892-universal.jar
boilerplate-1.7.10-6.0.0.jar
Bookshelf-1.7.10-1.2.0.jar
Botania r1.7-218.jar
buildcraft-7.0.21.jar
BuildcraftAdditions-1.7.10-2.2.2.jar
Carpenter's Blocks v3.3.5 - MC 1.7.10.jar
CB_ChickenChunks-1.7.10-1.3.4.19-universal.jar
CB_CodeChickenCore-1.7.10-1.0.7.46-universal.jar
CB_EnderStorage-1.7.10-1.4.7.36-universal.jar
CB_NotEnoughItems-1.7.10-1.0.5.111-universal.jar
CB_Translocator-1.7.10-1.1.2.15-universal.jar
CB_WR-CBE-1.7.10-1.4.1.9-universal.jar
ChestTransporter-2.0.3-MC1.7.10.jar
Chisel2-2.3.7.34.jar
chocolateQuest-1.7.10-1.0.jar
chunkgen-1.7.10-1.2.jar
Clay Worldgen v1.0.1.jar
clockworkphase-1.7.10_1.0f.jar
COFH_CoFHCore-[1.7.10]3.0.3-303.jar
COFH_CoFHLib-[1.7.10]1.0.3-175.jar
COFH_MineFactoryReloaded-[1.7.10]2.8.0-104.jar
COFH_NetherOres-[1.7.10]2.3.0-12.jar
COFH_RedstoneArsenal-[1.7.10]1.1.1-89.jar
COFH_ThermalDynamics-[1.7.10]1.1.0-161.jar
COFH_ThermalExpansion-[1.7.10]4.0.3B1-218.jar
COFH_ThermalFoundation-[1.7.10]1.2.0-102.jar
ColourfulPortals-1.4.2_for_1.7.X.jar
compactstorage-1.7.10-release-2.0.0.4-universal.jar
ComputerCraft1.73.jar
CookieCore-1.7.10-1.3.1-7.jar
customrecipes
customrecipes-1.7.10-4.7.jar
DanglingVanillaFixer-1.0.jar
Decocraft-v1.12b_1.7.10.jar
DT_DummyCore1.13.jar
DT_EssentialCraftv4.6.1710.63.jar
DT_EssentialThaumaturgy-1.1.1710.11EC(4.4.1710.37)TC(4.2.3.5).jar
dungeonpack-1.7.10-1.0.jar
ElectroMagicTools-1.7.10-2.0.0-CUSTOM_V4.1.jar
EnchantingPlus-1.7.10-3.0.2-d.jar
EnderIO-1.7.10-2.2.8.381.jar
EnderTech-1.7.10-0.3.2.375.jar
EngineersToolbox-1.2.2.1-BETA.jar
EnhancedPortals_1.7.10-universal-3.0.10.jar
EvilCraft-1.7.10-0.8.4.jar
ExtraCarts-1.7.10-b0.7.0.jar
ExtraTiC-1.7.10-1.0.3.jar
extrautilities-1.2.10.jar
Factorization-1.7.10-0.8.95(2).jar
FlatSigns-1.7.10-universal-2.1.0.19.jar
Flaxbeard'sSteamPower-1.7.10-0.28.7.jar
Floating Rails Beta v1.0.jar
fluxedCrystals-1.0.3.jar
Forbidden Magic-1.7.10-0.561.jar
forestry_1.7.10-3.6.3.20.jar
Gollum_Core_Lib.1.7.10-2.0.0Beta1.0.jar
GraviSuite-1.7.10-2.0.3.jar
Guide-API-1.7.10-1.0.1-20.jar
GUI_Waila-1.5.10_1.7.10.jar
GUI_WAILAPlugins-MC1.7.10-0.0.1-14.jar
HardcoreEnderExpansion  MC-1.7.10  v1.8.3.jar
Highlands-1.7.2-v-2.2.3.jar
Highlands.Integrator-1.7.10-0.1.0-2-universal.jar
hopperductmod-1.7.10-1.3.2.jar
IC2NuclearControl-2.2.5a-GoingForTheKill.jar
IC2_AdvancedSolarPanel-1.7.10-3.5.1.jar
IC2_AFSU-1.2.0a-Mustard.jar
IC2_industrialcraft-2-2.2.767-experimental.jar
IC2_WaterPower-1.7.10-0.3j.jar
IguanaTinkerTweaks-1.7.10-2.1.5.jar
IGW-Mod-1.7.10-1.1.5-22-universal.jar
IMM_adv-repulsion-systems-59.0.3.jar
IMM_advanced-machines-59.0.2.jar
IMM_connectedglass-59.0.2.jar
IMM_dimensional-anchor-59.0.3.jar
IMM_immibis-core-59.1.2.jar
IMM_immibis-microblocks-59.1.1.jar
IMM_immibis-peripherals-59.0.2.jar
IMM_infinitubes-59.0.5.jar
IMM_liquid-xp-59.0.1.jar
IMM_redlogic-59.1.11.jar
IMM_tinycarts-0.2.jar
IMM_tubestuff-59.0.4.jar
Iron-Chests-Mod-1.7.10.jar
Jabba-1.2.0a_1.7.10.jar
JACB-1.7.10-1.0.2.jar
Java7Checker  MC-1.7.10  v1.1.jar
legendgear-1.7.10-2.b.2.1.jar
logisticspipes-0.9.2.33.jar
LycanitesMobsComplete 1.11.0.6 [1.7.10].jar
magicalcrops-4.0.0_PUBLIC_BETA_3.jar
magicbees-1.7.10-2.3.4.jar
Mantle-1.7.10-0.3.2.jar
Mekanism-1.7.10-8.1.7.252.jar
MekanismGenerators-1.7.10-8.1.7.252.jar
MekanismTools-1.7.10-8.1.7.252.jar
Metallurgy-1.7.10-4.0.8.97.jar
MetallurgyCore-1.7.10-4.0.4.18.jar
minefactory-magicalcrops-compatibility-1.1.jar
MoChickens-1.7.10-1.6.2.jar
ModularArmour-1.7.10-0.0.10-CUSTOM.jar
ModularPowersuits-0.11.0.178.jar
ModularSystems-1.7.10-2.2.1.jar
MoreFurnaces-1.3.9-MC1.7.10.jar
More_Pistons-1.7.10-2.0.0Beta1.0.jar
MultiPageChest-1.3.4-MC1.7.10.jar
natura-1.7.10-2.2.0.1.jar
NBTEdit_1.7.10.jar
NEIIntegration-MC1.7.10-1.0.11.jar
NodalMechanics-1.7-1.0-7.jar
NotEnoughIDs-Tweaker-[1.7.10]1.2.0.jar
NotEnoughIDs-[1.7.10]1.2.0.jar
Numina-0.4.0.100.jar
OmnisCore-1.7.10 - 0.0.6-universal.jar
OpenBlocks-1.7.10-1.4.1.jar
OpenComponents-MC1.7.10-0.2.1.25-universal.jar
OpenComputers-MC1.7.10-1.5.16.32-universal.jar
OpenModsLib-1.7.10-0.7.1.jar
OpenModularTurrets-1.7.10-1.3.7-32.jar
OpenPeripheral-1.7.10-AIO-3.jar
OreDictionaryConverter-1.6.1.jar
Origin-1.7.10-5.0.2.jar
ParticleLib - 1.jar
PlanetguyLib-1.6.0.1.jar
PlayerAPI-1.7.10-1.2.jar
PneumaticCraft-1.7.10-1.9.4-91-universal.jar
PowerConverters-1.7.10-3.0.4.47.jar
ProjectBlue-1.1.4-mc1.7.10.jar
ProjectRed-1.7.10-4.7.0pre8.92-Base.jar
ProjectRed-1.7.10-4.7.0pre8.92-Compat.jar
ProjectRed-1.7.10-4.7.0pre8.92-Fabrication.jar
ProjectRed-1.7.10-4.7.0pre8.92-Integration.jar
ProjectRed-1.7.10-4.7.0pre8.92-Lighting.jar
ProjectRed-1.7.10-4.7.0pre8.92-Mechanical.jar
ProjectRed-1.7.10-4.7.0pre8.92-World.jar
QmunityLib-1.7.10-0.1.92-universal.jar
quantumAnomalies-1.7.10-0.0.5-UNIVERSAL.jar
QuarryPlus-1.7.10-2.0.3.jar
QuiverBow_1.7.10_b96.jar
Railcraft_1.7.10-9.6.1.0.jar
rancraftpenguins-1.7.10q.jar
RedstoneArmory-1.7.10-1.2.0-34.jar
RedstonePasteMod-1.7.10-1.6.2.jar
RemainInMotion-2.7.0.2.jar
RemoteIO-1.7.10-2.1.B0-universal.jar
RFDrills-1.7.10-1.4.3.jar
rftools-3.11.jar
rivalrebels-1.7.10J.jar
R_ChromatiCraft 1.7.10 V7e.jar
R_CritterPet 1.7.10 V7a.jar
R_DragonAPI 1.7.10 V7f.jar
R_ElectriCraft 1.7.10 V7e.jar
R_ExpandedRedstone 1.7.10 V7a.jar
R_GeoStrata 1.7.10 V7e.jar
R_MeteorCraft 1.7.10 V7a.jar
R_ReactorCraft 1.7.10 V7f.jar
R_RotaryCraft 1.7.10 V7f.jar
R_UsefulTNT 1.7.10 V7a.jar
simplefluidtanks-1.7.10-1.2.0.5.jar
SimplyJetpacks-MC1.7.10-1.3.2.jar
SmartCore-1.7.10-1.0.jar
SolarExpansion-Basic-1.4c.jar
SolarFlux-1.7.10-0.5a.jar
SoulShards-TOW-1.7.10-0.1-RC9-7.jar
sourcecodedcore-1.7.10-1.0.2-UNIVERSAL.jar
steamcraft2-1.7.10-B4.5.jar
TConstruct-1.7.10-1.8.5.jar
Technomancy - 0.10.k - 1.7.10.jar
Thaumcraft-1.7.10-4.2.3.5.jar
ThaumcraftGates-1.4.1.jar
ThaumcraftMobAspects-1.7.2-2A.jar
thaumcraftneiplugin-1.7.10-1.7a.jar
Thaumic Additions - 0.22.jar
Thaumic Machina-1.7.10-0.2.1.jar
ThaumicBases-1.3.1710.4.jar
thaumicenergistics-0.8.10.7.jar
ThaumicExpansion-1.7.10-3.0.0.jar
ThaumicExploration-1.7.10-1.1-53.jar
thaumichorizons-1.7.10-1.1.1.jar
ThaumicInfusion-4.21.jar
ThaumicPipes-1.7.10 - 1.2.1a-universal.jar
ThaumicTinkerer-2.5-1.7.10-164.jar
Thaumic_Upholstery-1.2_1.7.10.jar
ThermalRecycling-1.7.10-0.3.9.7.jar
ThermalSmeltery-1.7.10-1.2.1.jar
TMechworks-1.7.10-0.2.14.100.jar
TravellersGear-1.7.10-1.16.4.jar
TSteelworks-1.7.10-1.1.0-16.jar
ttCore-MC1.7.10-0.1.1-77.jar
twilightforest-1.7.10-2.3.7.jar
WarpTheory-1.7-1.0-24.jar
WaslieCore-1.1_B44.jar
Wawla-1.3.1-1.7.10.jar
WholeTreeAxe-1.1.9-MC1.7.10.jar
witchery-1.7.10-0.24.1.jar
WitchingGadgets-1.7.10-1.1.9.jar
worldedit-forge-mc1.7.10-6.0-beta-01.jar
Ztones-1.7.10-2.2.1.jar
ZZZZZ Custom Configs-2.1.0.jar
[1.7.10-10.13.0.1198]ArchimedesShipsPlus-universal-1.7.10.B-Plus.jar
[1.7.10-10.13.2.1230]Large Sign-2.0.jar
[1.7.10] SpaceCore 0.7.12.jar
[1.7.10] Survival Wings 1.2.6.jar
[1.7.10]ExtendedWorkbench v1.2.1.1.jar

**Comment by fewizz** [comment]
Модпак и сломанный мир в студию.

**Comment by Solarstrike** [comment]
I've experienced the same issue, and the world gen is HILARIOUS.

**Comment by VasyaOrk** [comment]
Модпак.

https://drive.google.com/file/d/0B8jr0bxZv6gRSEFzcE5zdGU1YXM/view?usp=sharing

Отдельно клиент и сервер (нас играет 4 человека)
Запаковано в архив. Запаролено. (потому что google drive и .jar файлы (((( )
password :   1
---
Запуск через .bat файлы
(время запуска (i7-3771, 16GB RAM шина 1800 МГц) как клиента так и сервера - порядка 6-8 минут)
Глючный мир в комплекте.
Перенастройка на Kcauldron 150 или 155, удаление из клиента FastCraft, Optifine или обоих - ничего не дает.
---
Создание нового мира : 
Создается и обслуживается (мобы, добыча, выпадание и возможность подобрать блоки) квадрат 16х16 чанков. Все что за пределами - подгружается с глюками (кубами со стороной 16 блоков), при попытке действовать в глючной области - через некоторое время сервер рвет соединение.
Глючная область не пустая, она ведет себя как невидимая (мобы стоящие на воздухе, атаки из пустоты, звуки из пустоты, невидимая стена)
Единственные блоки, которые прорисованы в глючной области - это вентиляторы из Geostrata
При перезаходе на сервер: если был внутри квадрата 16х16 - квадрат прорисовывается четко, все недопрорисованное за пределами квадрата - исчезает
Если был в глючной области - оказываешься в пустоте.
При перезапуске сервера начинает глючить и область 16x16 чанков.
---
миникарта накапливает информацию отдельно. Накопленное живет в клиенте в mods\VoxelMap и при пересоздании мира не удаляется.
---
Прошу прощения за "многобукв"

**Comment by fewizz** [comment]
надеюсь мне хватит оп. =P

**Comment by fewizz** [comment]
Включаю, комп не вырубается, оп хватает, но видеокарта накрывается... Пора менять. И всё же, на днях проверю модпак на ноуте друга. Такие дела. =P

**Comment by fewizz** [comment]
Оперативки мало. Мне придется связаться с вами через скайп. :smile:

**Comment by VasyaOrk** [comment]
skype : vasyaork

**Comment by fewizz** [comment]
Fixed? https://drive.google.com/file/d/0B0GYhmakgvItU3k4MWVLMlRhS1U/view?usp=sharing

**Comment by VasyaOrk** [comment]
Yes!
Version 1.2.0 not work with KCauldron. Irrelevant with or without mods.
Version 1.3.0 work!

**Comment by fewizz** [comment]
Yay :smile:  . Solarstrike?

**Comment by Solarstrike** [comment]
@fewizz Does this fix #16 as well?

**Comment by fewizz** [comment]
No. Tweaker not changed.

**Comment by crunkazcanbe** [comment]
What mod gives you the bar at the top in the screen shot ?
