### ISSUE TITLE
Request - Extend Dimensional IDs

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [fewizz/NotEnoughIDs#15]
I am super 100% grateful for such a otherwise Prometheus level of mod. You essentially have done what I was told directly was not possible! 

As o great coder if you could crush the limits for me yet again as I have run into issues in the past with dimensional IDs.

**Comment by Adaptivity** [comment]
This definitely will take time. Don't expect this soon.

**Comment by Solarstrike** [comment]
Dimensional ID's are already infinite.

**Comment by DPxKnightxZero** [comment]
They are not unlimited you have a limit exactly = to the biome limit of 255

**Comment by Solarstrike** [comment]
@DPxKnightxZero Weird, it seems to be infinite for me.
