### ISSUE TITLE
Fastcraft-1.22-ctest14: again chunk loading/saving issues

### ISSUE THREAD

**Issue by walkerjonny** [fewizz/NotEnoughIDs#16]
Fastcraft-1.22-ctest13 seems to work but with the new Fastcraft-1,22-ctest14 those chunk loading/saving issues are happening again.
Maybe you want to fix that.

**Comment by Solarstrike** [comment]
Can confirm.

**Comment by Adaptivity** [comment]
An update on this: This probably not going to be fixed soon.
The reasons why:
1) Compatibility will break with every Fastcraft update
2) ctest14 have some nasty bugs reported on its forum. If we will support ctest14 then we should drop support for ctest13.
3) It's still a test version and Player have no ETA for something more stable.
So, just use ctest13 for now.

**Comment by Adaptivity** [comment]
Apparently, @fewizz just fixed this.

**Comment by walkerjonny** [comment]
Where can we get a download version for that fix? 
Or is there a somewhere repository that I need to compile to get that fix?

**Comment by fewizz** [comment]
From issue #17

**Comment by walkerjonny** [comment]
Thank you very much!
I'll test it asap!

**Comment by SvEgiiVEteR** [comment]
need to fix fastcraft-1.22-ctest15
http://forum.industrial-craft.net/index.php?page=Thread&postID=194889#post194889
fastcraft-1.22-ctest15.jar
NotEnoughIDs-[1.7.10]1.3.0.jar
Thaumcraft-1.7.10-4.2.3.5.jar
BiomesOPlenty-1.7.10-2.1.0.1394-universal.jar

**Comment by fewizz** [comment]
https://drive.google.com/file/d/0B0GYhmakgvItWldjcHpmZnA4N2s/view?usp=sharing
https://drive.google.com/file/d/0B0GYhmakgvItRDdrUTdKY2I5dlU/view?usp=sharing
FOR TESTING. If fixed, will be release(without UBC sup. :cry: )

**Comment by SvEgiiVEteR** [comment]
fastcraft-1.22-ctest15
Thanks problem seems solved!
if not write))

**Comment by fewizz** [comment]
Как думаешь, ветерок, релизать? :smile:

**Comment by SvEgiiVEteR** [comment]
хе))  думаю через час скажу ...проверю хотя бы...

**Comment by fewizz** [comment]
ждус.

**Comment by SvEgiiVEteR** [comment]
все хорошо карта загрузилась, щас на ней. раньше даже после того как фаст крафт обновил пропал кусок карты после даунгрейда до 14  версии.не чанками а как буд то разлом в мире...притом красивый))) модов много...340. думаю можно выложить. мод должен как минимум загружаться и это уже есть)) про баги если есть остальные игроки напишут. 
а мы знакомы? или просто по сборкам моим слышали обо мне?

**Comment by fewizz** [comment]
нет, прост на форуме ic2 видел тебя, а сборочки то я свои делаю :smile: .

**Comment by SvEgiiVEteR** [comment]
а где можно поглядеть ваши) ещё и из казани я тоже не далеко)йошка)

**Comment by fewizz** [comment]
А яих для себя делаю О_О. А где можно посмотреть на твои?

**Comment by SvEgiiVEteR** [comment]
на рутрекере viewtopic.php?t=4365464 но давно уже не делал) тоже для себя но в народ выкладывал

**Comment by Bogdan-G** [comment]
"и да рудой из UBC не пользуюсь так что не критично))" Но я пользуюсь UBC, но в клиенте не стоит самый новый ФК из-за тестов плеера в том числе.

**Comment by fewizz** [comment]
@Bogdan-G , https://github.com/fewizz/NotEnoughIDs/issues/17

**Comment by Bogdan-G** [comment]
@fewizz я выключил убификацию, т.к. она в моем модпаке не работает (ванила руды УБС смог заменить, а из остальных модов нет) т.к. я выкл генерациюванилла руд. А для руд из модов нужно  ставить дополнительный мод, который плохо обновляется.

**Comment by fewizz** [comment]
Почему ж, UBC ore registrar вродь часто обновляется...

**Comment by Bogdan-G** [comment]
Но руды грега остаются без замены как и руды термалки, либо мод ломает запуск игры либо создание мира.
