### ISSUE TITLE
Underground Biomes Constructs ore replacement failing for mod blocks (with IDs > 255?)

### ISSUE THREAD

**Issue by Mysteryem** [fewizz/NotEnoughIDs#17]
UBC introduces a large number of new stone types. To go along with this, it adds variants of the vanilla ores with stone backgrounds to match the surrounding stone (these are added as separate blocks, not dynamic texture changing stuff like gregtech). It has support via API for adding ores from other mods to be 'UB-ified'. Usually, this works flawlessly, however, with Not Enough IDs installed, it no longer works for some ores.

What I think the cause is (hence the title of this issue), is that Not Enough IDs has accidentally undone one of Forge's many changes to allowing up to block IDs of 4095 from being accessed and modified in the world (up from vanilla's maximum of 255).

In the modpack I have with both UBC and Not Enough IDs, as I added more mods to the pack, I noticed that the UB-ification of mod ores started to stop working, the more mods added, the less ores were UB-ified.

I decided to rename both Big Reactors and Thermal Foundation so that they loaded earlier. Once done, the Big Reactors Yellorite ore and all of the thermal Foundation ores were being UB-ified correctly (along with IC2's ores)

Taking dumps of the Blocks, the highest ID of an ore block that was being UB-ified was IC2s Uranium ore with ID 183, the lowest ID of an ore block that was not being UB-ified was Mekanism's Osmium ore with ID 488

Here's a list if interested:

Working blocks

| ID  | Ore Block |
| :---: | :---------: |
| 165 | Thermal Foundation Ores |
| 183 | Big Reactors Yellorite |
| 195 - 198 | IC 2 Ores |

Not working blocks (not an exhaustive list)

| ID  | Ore Block |
| :---: | :---------: |
| 488 | Mekanism Ores |
| 910 | Thaumcraft Ores |
| 1237 | Applied Energistics Certus Quartz |
| ⋮ | ⋮ |
| 4044 | Project Red Ores |

Note that removing enough mods to get under the 4096 block ID cap and removing Not Enough IDs causes all the ores to be UB-ified correctly. Re-adding Not Enough IDs (while still under the 4096 cap) will make most ores stop being UB-ified again.

**Comment by Adaptivity** [comment]
Need to look into this carefully. It's also possible that ubifi'ed ores can spawn on surface. However, it's very random and needs a lot of testing.

**Comment by Mysteryem** [comment]
I did some more experimentation and I can almost assuredly confirm that somewhere, ints are being stored into bytes. The UB-ification method for say, Yellorite ore (Yellorite has ID 183, metadata 0) is converting all blocks whereby the 8 least significant bits of their ID is the same, such as Botania's Mystical White Flowers (ID 951, metadata 0) [(951 - 183) % 256 = 0] into UB-ified Yellorite. I also noticed Natura:floraleavesnocolor (ID 1733) getting turned into UB-ified IC2 Uranium (ID 197) and Thaumcraft Nodes (ID 933, metadata 0) getting turned into UB-ified Thermal Foundation Copper (ID 165, metadata 0). 

This is kind of a problem as with the current IDs forge is assigning me for example, Extra Biomes XL fir logs are being turned into diamond ore and 1/3 of UB-ified coal ore is being further UB-ified into diamond ore.

Bizarrely though, I've found that some blocks are unaffected. In the below image, you can see one chunk with Mystical White Flowers and the other chunk with Red Granite Yellorite Ore (what looks like a single Mystical White Flower is actually a Tall Mystical White Flower, which is also a dead giveaway as to what the Yellorite ore blocks are meant to be)
![image](https://cloud.githubusercontent.com/assets/495015/9948780/ef510d7a-5d9d-11e5-8f8d-fd21e0f18a9e.png) however this doesn't appear to be chunk based as I've found some chunks whereby the UB-ification has occured on some ores, but also whereby it's not occured (all in the same chunk).

It's possible this second thing isn't a NotEnoughIDs bug, even if it is, it's not much of a problem as it won't hurt seeing a non-UB-ified ore from time to time.

**Comment by Adaptivity** [comment]
@fewizz probably fixed this but it's need testing. I'll say him to drop new build for you to test.

**Comment by fewizz** [comment]
https://drive.google.com/file/d/0B0GYhmakgvItUUNUaDljOVJ6eTA/view?usp=sharing
Tweaker - https://drive.google.com/file/d/0B0GYhmakgvItUUNUaDljOVJ6eTA/view?usp=sharing

**Comment by Mysteryem** [comment]
There's no public access to the tweaker file, I'll test without it and fastcraft for now.

**Comment by Mysteryem** [comment]
Crashed with "maximum id range exceeded" for both: https://gist.github.com/Mysteryem/f84f415587dc7c94f3ea (crash report without tweaker and fastcraft was basically the same)
Was this build meant to be installed somewhere other than directly inside the mods folder?

**Comment by fewizz** [comment]
Lolwhat? I will look into this. No.

**Comment by Mysteryem** [comment]
If it's useful, here's the full fml log: https://gist.github.com/Mysteryem/aef11a7f932a94b627d5

**Comment by fewizz** [comment]
https://drive.google.com/file/d/0B0GYhmakgvItM00xUVZSQmVNMFE/view?usp=sharing

**Comment by Mysteryem** [comment]
The new version appears to have made no difference, the natura leaves are still turning into uranium and the mystical white flowers are still turning into yellorite.

**Comment by fewizz** [comment]
Ok, work in progress. :smile:

**Comment by Adaptivity** [comment]
@Mysteryem did you tested this on new world?

**Comment by Mysteryem** [comment]
Yeah, a new world each time, I tried once with the BOP world type and once with the default, same things happened.

**Comment by Adaptivity** [comment]
@Mysteryem can you give your modpack to us? We need mods and config folders.

**Comment by Mysteryem** [comment]
Have you got somewhere that I can privately message you a link to the pack?

**Comment by fewizz** [comment]
hazeevaidar@yandex.ru

**Comment by Mysteryem** [comment]
Link to the modpack has been sent, let me know if you have any issues.

If you want to make it easier to test the ore replacement, you can add something like
```
"DEBUG": {
        "template": "uniform",
        "block": {"name": "ExtrabiomesXL:cornerlog_redwood", "weight":50},
        "material": "minecraft:air",
        "clusterSize": 4,
        "numClusters": 2,
        "minHeight": 50,
        "maxHeight": 200,
        "retrogen": "true",
        "biomeRestriction": "none",
        "biomes": [],
        "dimensionRestriction": "blacklist",
        "dimensions": [
            -1,
            1
        ]
    }
```
to one of the config/cofh/world .json files. (corner redwood logs turn into diamond ore for me, so that should happen for you as well if Forge allocates the block IDs the same)

**Comment by Adaptivity** [comment]
We need UBC source which is not available right now. UBC author said that he will update source on his Github repository when he will return from vacation. Until that, can't fix this.

**Comment by fewizz** [comment]
I returned to work -_-.

**Comment by Mysteryem** [comment]
This is what I can see that looks like it would be an issue. 

UBC has a method (also the method below) that uses the code of some of the vanilla methods https://github.com/Zeno410/UndergroundBiomesConstructs1.7/blob/master/src/exterminatorJeff/undergroundBiomes/worldGen/BiomeUndergroundDecorator.java#L210 which gets block IDs here https://github.com/Zeno410/UndergroundBiomesConstructs1.7/blob/master/src/exterminatorJeff/undergroundBiomes/worldGen/BiomeUndergroundDecorator.java#L240

NotEnoughIDs changes some of the vanilla methods that UBC has copied code from: https://github.com/fewizz/NotEnoughIDs/blob/master/src/main/java/ru/fewizz/idextender/IETransformer.java#L229

Notice how NEIDs effectively overwrites net.mincraft.world.chunk.storage.ExtendedBlockStorage.getBlockByExtId, replacing it with https://github.com/fewizz/NotEnoughIDs/blob/master/src/main/java/ru/fewizz/idextender/Hooks.java#L89.

In the UBC code I linked above, it is getting the block ID in the same way as vanilla methods, but because it's using copied code of vanilla methods instead of vanilla methods, it's bypassing the methods that NEIDs has transformed.

**Comment by fewizz** [comment]
BC has a method (also the method below) that uses the code of some of the vanilla methods https://github.com/Zeno410/UndergroundBiomesConstructs1.7/blob/master/src/exterminatorJeff/undergroundBiomes/worldGen/BiomeUndergroundDecorator.java#L210 which gets block IDs here https://github.com/Zeno410/UndergroundBiomesConstructs1.7/blob/master/src/exterminatorJeff/undergroundBiomes/worldGen/BiomeUndergroundDecorator.java#L240"

Already changed in latest build.

**Comment by fewizz** [comment]
[now?](https://drive.google.com/file/d/0B0GYhmakgvItbW1WUVJGOEJTQlU/view?usp=sharing)

**Comment by fewizz** [comment]
[For testing.(without fastcraft!)](https://drive.google.com/file/d/0BwY_2FEZWt8dVzJrdGVNNVFZcGc/view?usp=sharing)

**Comment by Adaptivity** [comment]
@Mysteryem can you test [this version](https://drive.google.com/file/d/0B0GYhmakgvItZjMzVmtoT2RSY2s/view) please?

**Comment by Mysteryem** [comment]
With https://drive.google.com/file/d/0B0GYhmakgvItZjMzVmtoT2RSY2s/view (adaptivity) crash maximum ID range exceeded: https://gist.github.com/Mysteryem/27b882ec288f09216435 no tweaker, no fastcraft
With https://drive.google.com/file/d/0BwY_2FEZWt8dVzJrdGVNNVFZcGc/view?usp=sharing (fewizz) crash: https://gist.github.com/Mysteryem/edd7c621430931990df3 no tweaker, no fastcraft

**Comment by Adaptivity** [comment]
Sorry, yet another problem. 1.4.0 currently not extending ids at all -_- We'll inform you when the fix is available.

**Comment by Adaptivity** [comment]
@Mysteryem [NotEnoughIDs-1.4.0Test3](https://drive.google.com/file/d/0B0GYhmakgvItMGdUVWk3d1pBTlk/view?usp=sharing) I really hope this build will work for you. Please test if you have time.

**Comment by Adaptivity** [comment]
This should be fixed in the latest NEID version. Remember to use latest test version of UBC and NEID 1.4.0 (available on Curse)
