### ISSUE TITLE
Issue - Some mods are not respecting the block ID increase.

### ISSUE THREAD

**Issue by DPxKnightxZero** [fewizz/NotEnoughIDs#19]
using factcraft 1.21 only client side. Magical crops appears to ignore ID extension. Using MCBeta 5

**Comment by Solarstrike** [comment]
Have you updated to the developmental builds?

**Comment by DPxKnightxZero** [comment]
Where are those?

**Comment by Solarstrike** [comment]
Fastcraft 1.22c14 builds. They're on the FC forum post.

**Comment by Solarstrike** [comment]
Also, use #20 please.

**Comment by DPxKnightxZero** [comment]
Can I please have a direct link?

**Comment by Solarstrike** [comment]
http://goo.gl/NPmuQa

**Comment by DPxKnightxZero** [comment]
This is new latest version http://files.player.to/tmp/fastcraft-1.22-ctest15.jar also it seems to be greatly fixed.

**Comment by Solarstrike** [comment]
ah

**Comment by Adaptivity** [comment]
Closing as no info was provided.
