### ISSUE TITLE
Mod Support

### ISSUE THREAD

**Issue by Solarstrike** [fewizz/NotEnoughIDs#20]
Please note any mods that feature a lack/limited support for NEID here.
- Magical Crops (#19) [more info required]
- Underground Biomes (#17) [should be fixed but not tested] 
- Tinkers' Construct (#23) 
- MapWriter (#11)
- FastCraft (serverside) (#22) (fixed)

**Comment by Adaptivity** [comment]
DivineRPG issue was closed. @DPxKnightxZero is it fixed?
Magical Crops need more info about it. Which blocks are not support ID extension? How did you find out that Magical Crops ignore ID extension? Crash? Or what?

**Comment by DPxKnightxZero** [comment]
I will test magical crops today however in the latest build Divine RPG seems to be respecting IDs though the real test will be when you add support for Dims and Biomes because the mod TheShadows creates a darkverse clone of all mods present since I have about 70+ Dims and 190+ Biomes and 9000 blocks that will end up being the real test.

**Comment by Adaptivity** [comment]
I dunno which version you should test. You said it's not respecting block ID increase(#19) so you should know better. But I guess latest maybe?

**Comment by DPxKnightxZero** [comment]
I forgot how I got my hands on a private release of magical crops ... it was on a fluke ... maybe I will figure it out. If nothing else I will just test the curse release ... (I know however the curse release has annoying duplication bugs.)

**Comment by Solarstrike** [comment]
Added TiC. #23

**Comment by Adaptivity** [comment]
Need someone who will test UBC + UBC Ore Registrar mod + ton of mods which adds new ores to the world generation. Things to check: 1) Check if ores appears on the surface (with big amount) 2) Check if ores randomly appears on the dirt (They may replace Botania flowers)
