### ISSUE TITLE
Problems with Tinkers' mods ID usage

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [fewizz/NotEnoughIDs#23]
So after installing this in my latest update it wrecked iguana tweaks in a way that made my modpack unplayable :/ the glitch only seems to take place after the NotEnoughIDs Extension table takes place. The symptoms are as follows.

Swords claim they have a bad ID table.
When vanilla tools are allowed they don't respect the config.
Some vanilla tools have glitchy textures.
Some vanilla tools suddenly stop working.

I know it has to do with an interaction of this mod and that one because after removing this mod it respected the config as well as the ID table.

DEV NOTE PLEASE READ EVERYONE:
As a temporary fix you should add "1" to Tinkers' mods .jar names. Example: "IguanaTinkerTweaks-1.7.10-2.x.x.jar" -> "1IguanaTinkerTweaks-1.7.10-2.x.x"

**Comment by Adaptivity** [comment]
As a temporary fix I suggest you to rename "IguanaTinkerTweaks-1.7.10-2.x.x.jar" to "1IguanaTinkerTweaks-1.7.10-2.x.x" and same for TinkersConstruct .jar file. Let me know if it fixes the issue.

**Comment by DPxKnightxZero** [comment]
May I inquire is to what that will accomplish? (It helps me debug issues in the future when similar issues arise. Also it allows me a great deal of insight on when potential symptoms could be later.)

**Comment by Adaptivity** [comment]
In theory it can help you. It's just a guess. If you change .jar names, these mods will be loaded first, so they will fill vanilla ids (4096 range) first. And the issue probably will not arise. Just test this on new world with same modpack.

**Comment by DPxKnightxZero** [comment]
Alright confirmed that fixed it. The mods are now working correctly so that should help with an actual fix :D glad I could help you notice.

**Comment by mrammy** [comment]
What other mods do you have installed? I'm not seeing this issue in my pack and I have both ITT and TinkersConstruct both installed without needing to rename them.

**Comment by DPxKnightxZero** [comment]
Its fixed ... what difference would it make? If I have an issue I report bing bang boom. :D

**Comment by Adaptivity** [comment]
No, it's not fixed. It's just a temporary solution. We need to make it work without renaming the .jars.

**Comment by DPxKnightxZero** [comment]
Apologies; I guess I was just happy it worked at all.
