### ISSUE TITLE
Place Holder - Mod Compatibility - Devs Descussing Mod Tweaks and Issues for Fastcraft and NotEnoughIDs

### ISSUE THREAD

**Issue by DPxKnightxZero** [fewizz/NotEnoughIDs#25]
I am creating this thread to network devs on the dev of personal mods and allowing each dev to work in harmony with fastcraft and notenoughids.

**Comment by Solarstrike** [comment]
I partially had the same idea with #20.

**Comment by DrZed** [comment]
https://github.com/HxCKDMS/HxCEnchants/issues/37
Does this have something to do with this?

**Comment by Adaptivity** [comment]
Use @Solarstrike issue.
