### ISSUE TITLE
Unrelated request - Dimensional Door ID Table fixes

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [fewizz/NotEnoughIDs#26]
There is an amazing mod called "Dimenionsal Doors" Unfortunatly the way it currently handles Dimensional IDS is poor at best there is a glitch which causes it to re-Assign an ID when a server reloads and since the Dims are not hard set it sometimes overwrites existing ID tables making it so a world corrupts. I was wondering if you could attempt to fix it since your team seems good at ID table management. By the way it is very much open source.

https://github.com/CannibalVox/DimDoors/releases

**Comment by fewizz** [comment]
I will look into this...

**Comment by DPxKnightxZero** [comment]
Thank you so much <3 you really are a godsend to the minecraft modding community! <3
