### ISSUE TITLE
World loading issue

### ISSUE THREAD

**Issue by Noku269** [fewizz/NotEnoughIDs#29]
this isn't a crash but when using this mod I experience weird world loading in a way that's 16x16x16 chunks of area not rendering until I break some part of it or update it in anyway, this is not a chunk error as one would expect but rather a "section" error as I would call it (I cant think of any other thing to name it) for it is not all the way down but either the surface of bottom of the world in seemingly random areas

**Comment by Bogdan-G** [comment]
mod list? version mod? more info!

**Comment by fewizz** [comment]
Please. try this https://drive.google.com/file/d/0BwY_2FEZWt8dc09XUE9aVDBUY00/view?usp=sharing
and please, backup your world.

**Comment by Keyarose** [comment]
I had the same issue while using NotEnoughtIDs 1.4.2.  Upgrading fastcraft from 1.21 to 1.22-ctest17 fixed it for me.
