### ISSUE TITLE
FastCraft compatibility

### ISSUE THREAD

**Issue by Solarstrike** [fewizz/NotEnoughIDs#3]
I know NEIDs is currently incompatible with FC 1.21. Crashes haven't occured in 1.22c11 or c13. However, chunkloading is horrendous across both versions. I have contacted Player to see if the problem is on his end or not.

**Comment by Adaptivity** [comment]
I removed comments from commits (commits not for discussions). Use this issue for discussion.

**Comment by Solarstrike** [comment]
Got it.

**Comment by fewizz** [comment]
![2015-08-10_23 45 28](https://cloud.githubusercontent.com/assets/8060034/9183767/fe65ce38-3fb9-11e5-8a2e-610ac2388ee5.png)
yay =P

**Comment by Solarstrike** [comment]
Woohoo! Any signs of a release soon?

**Comment by fewizz** [comment]
Please test it with large modpack: 
https://drive.google.com/file/d/0B0GYhmakgvItS0l6c2pKSFQ0dVU/view?usp=sharing
https://drive.google.com/file/d/0B0GYhmakgvItTUVaZVU1MW5sZm8/view?usp=sharing
(Yes, now 2 files.)

**Comment by Solarstrike** [comment]
Tested with RR w/258 mods, frames issues.

**Comment by Adaptivity** [comment]
What are your PC specs? Are you getting low framerate or framerate drops?

**Comment by fewizz** [comment]
list of mods pls.

**Comment by Solarstrike** [comment]
Drops. I don't know my specs exactly.

**Comment by Adaptivity** [comment]
Fastcraft compatibility is live. @Solarstrike if you still experience issues with FPS, open a new issue with following information:
1) Computer specs
2) List of mods (Printscreen your mods folder and upload screenshot to imgur or other pic website)
3) An .zip archive with mods and config folder.
4) If it applies only to existing world, upload your world folder.

**Comment by Solarstrike** [comment]
Reopen on account of #16.

**Comment by Adaptivity** [comment]
Fastcraft compatibility still working, it's just need an update. Not need to reopen this.
