### ISSUE TITLE
DataWatcher

### ISSUE THREAD

**Issue by Bogdan-G** [fewizz/NotEnoughIDs#30]
/* lang:ru */
Такого исуса не нашел О_о, что то наподобие запроса-плашки.
Заметил что в TODO он есть, вопрос: когда будет добавлен? С таким набором модов я постоянно натыкаюсь о нехватке (варнинги или циклы вечные или краши): http://imgur.com/vL2rg1U.png

Чаще всего орет MFQM что его заданные значение украли.
http://www.minecraftforge.net/wiki/Datawatcher
следуя этому и еще др данным датаватчеры можно исп от 20 до 31, все ост занято ванилой/кузницей или чем то еще? 

Несколько модов каждый по 3-4 датаватчера и лимит исчерпан. Зачем вообще так глупо ограничивать в 32 всего?
<hr>
/* lang:en */
This Issues not found O_o, that something like query-slips.
TODO noticed that it is the question: when will be added? With this set of mods I always stumble on the lack of (warnings or eternal cycles or crash): http://imgur.com/vL2rg1U.png

Most often yells MFQM that it sets the value of stolen.
http://www.minecraftforge.net/wiki/Datawatcher
Following this and other data can be Datawatcher's use from 20 to 31, all occupied East vanilla/forge or something else?

Several mods every 3-4 Datawatcher's and the limit is exceeded. Why do we so stupid to limit the 32 total?

**Comment by fewizz** [comment]
"Исправлено" в 1.4.1

**Comment by Solarstrike** [comment]
What does he say @fewizz?

**Comment by fewizz** [comment]
About DataWatcher limit(32), and incompatibilities with "More Fun Quicksand Mod".

**Comment by SvEgiiVEteR** [comment]
@fewizz а мод 150 с без лимита на биомы будет это исправление?

**Comment by fewizz** [comment]
@SvEgiiVEteR , так вотж https://github.com/fewizz/NotEnoughIDs/issues/31#issuecomment-167338136 без биомов

**Comment by SvEgiiVEteR** [comment]
@fewizz не, я всмысле БЕЗ лимита) что бы и биомы были раширены и DataWatcher.

**Comment by fewizz** [comment]
Будет. Проблема в том, что в некоторых модах стоит своя проверка. Если в конфигах пропишешь Больше ID > 31, мод автоматом ставить дефолтное значение...

**Comment by SvEgiiVEteR** [comment]
они часто такое пишут... но в некоторых и нет проверки. по этому можно их править...
не давно столкнулся с модом AoA2
поправил
datawatcher {
    I:CreationValue=23
    I:EnergyValue=22
    I:SoulValue=24
    I:Thermal=25
но думаю что не которые уже заняты..
