### ISSUE TITLE
problem with NotEnoughIds

### ISSUE THREAD

**Issue by lightning02** [fewizz/NotEnoughIDs#31]
https://github.com/MinecraftForkage/MinecraftForkage/issues/10#issuecomment-165965926

**Comment by Solarstrike** [comment]
Hello?

**Comment by lightning02** [comment]
Hi man :( i have a big problem.. check in the link i've posted here.. can you help me?

**Comment by Solarstrike** [comment]
I don't run this project, I'm just an assistant.

@fewizz, can you help?

**Comment by fewizz** [comment]
Try this. https://drive.google.com/file/d/0BwY_2FEZWt8dTXhKZGE2UG5UMHM/view?usp=sharing
Firstly Enable RemoveInvalidBlocks option in NEID config file.
(and please, backup your world)

**Comment by lightning02** [comment]
oh man.. you're the numer one, definetly!
i created a new world and it works.
anyway it seems that when you walk forward and try to rotate the camera at left or right side sometime it doesen't work and you remain stuck with the camera aiming only straight in front of you.
i don't know if its a problem caused by NEID or other mods behaving weird.

**Comment by Bogdan-G** [comment]
Confilict gen world? Biome decorator?

**Comment by lightning02** [comment]
yes, some conflict world generating but i'm not sure if is biome decorator. 
Would you like take a look to the latest log?
I guess is something related with RemainInMotion and another mod which has this item "alchemicalwizardryBooks"; but i cant really figure out what exactly is. 
You can see that in the latest log.
http://pastebin.com/AvvWbyKB

**Comment by Solarstrike** [comment]
RIM worked fine with NEID for me.

**Comment by Bogdan-G** [comment]
@lightning02 ohh, you have to throw the file fml-latest-log

**Comment by lightning02** [comment]
Wew, ops :/ sorry
Here it is https://copy.com/lIJMB7KzBfQutl2R/fml-client-latest.log?download=1
It was a bit too long for pastebin ^^''
