### ISSUE TITLE
Port to 1.8.9 error I mean 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [fewizz/NotEnoughIDs#33]
The performance for 1.8.9 is insane and with this mod possibilities are legit endles

**Comment by Adaptivity** [comment]
There are no need for this now since there are just not so many mods on 1.8. But... maybe... sometime...

**Comment by DPxKnightxZero** [comment]
thank you :D I must have missed that!

**Comment by Adaptivity** [comment]
let's keep this open @fewizz still might port this in future (but not soon).

**Comment by DPxKnightxZero** [comment]
Understood! :)

**Comment by DPxKnightxZero** [comment]
I would actually like to change the request to 1.10.2 since it has 100% stable shader-mod support

**Comment by fewizz** [comment]
Maybe :s

**Comment by RavensFlight92** [comment]
thank you for considering it

**Comment by DPxKnightxZero** [comment]
Okay so your going to love this ... 1.10.2 has very mixed support in terms of mod upkeep and just like when 1.6.4 was discontinued we are losing hundreds of gem mods ... Anyways I was wonding if you could do 1.8.9 first and then 1.10.2 because 1.10.2 is slow to have mods updated and now mojang is pushing minecraft 1.20.0 which is annoying because I am sure they will greatly screw with something.

**Comment by Hypsellis** [comment]
Why are you not using the code of ExtendedMetadatas for helping you to update and improve NotEnoughID to 1.10.2 ? The author of ExtendedMetadatas have abandoned his mod and haven't more the time for continuing it. I suppose he wouldn't disagree that someone continue the mod at its place.

**Comment by fewizz** [comment]
Port for 1.10.2 will be soon :3

**Comment by Hypsellis** [comment]
Awesome new. <3

**Comment by fewizz** [comment]
(Link)[https://drive.google.com/file/d/0BwY_2FEZWt8ddEdrNm5JSGpSUFU/view?usp=sharing] . Not tested with other mods.

**Comment by Hypsellis** [comment]
It seems to work fine. Thanks a lot for the update, it's awesome. <3
Does it extend metadata item id limit ?

**Comment by fewizz** [comment]
Only block ids. And, please, try to place some blocks with id > 4096 in world. Thanks.

**Comment by Hypsellis** [comment]
I will try when I will have enough mod which exceed 4096 id limit. ;)

**Comment by fewizz** [comment]
Ok :3

**Comment by DPxKnightxZero** [comment]
I will test it like crazy ; thank you fewizz!

**Comment by DPxKnightxZero** [comment]
Here is proof of no crash after a lot of ids are used. 

https://www.dropbox.com/s/g6je1ashfinn1s1/Minecraft%20proof%20of%20a%20lot%20of%20ids%20used..PNG?dl=1

**Comment by DPxKnightxZero** [comment]
Okay I lied after reboot it seems to crash hard 

Complete Log 
https://gist.github.com/DPxKnightxZero/45fd0fc516e5985900753ced29a53419

Crash Log
https://gist.github.com/DPxKnightxZero/c4f2160fb27141f1acc3d4e72672a0a4

**Comment by Hypsellis** [comment]
Like I told before, you should use the code of ExtendedMetadatas for helping you to update and improve NotEnoughID to 1.10.2. https://minecraft.curseforge.com/projects/extendedmetadata?gameCategorySlug=mc-mods&projectID=231466

**Comment by DPxKnightxZero** [comment]
There is no 1.10.2 release

**Comment by fewizz** [comment]
DPxKnightxZero, skill be fixed.

**Comment by fewizz** [comment]
[lnk](https://drive.google.com/file/d/0BwY_2FEZWt8dOHF2ZGxFVmpQM2c/view?usp=sharing)

**Comment by fewizz** [comment]
@Hypsellis , needless, thanks.

**Comment by DPxKnightxZero** [comment]
Crashlog
https://gist.github.com/DPxKnightxZero/7f0acef84cadc0791daec3f4fd56b058

Full Log
https://gist.github.com/DPxKnightxZero/99efb0a35724965d3f3a3529ba3dea30

**Comment by fewizz** [comment]
@DPxKnightxZero , can you give me your modpack?

**Comment by DPxKnightxZero** [comment]
Yes not a problem!

**Comment by fewizz** [comment]
@DPxKnightxZero just mods and configs folder. If something won't work, i will fix probem myself. (Maybe I misunderstood the question xD (sorry for english))

**Comment by fewizz** [comment]
@DPxKnightxZero ? ;3

**Comment by DPxKnightxZero** [comment]
Hey I have to rebuild a modpack I want to rework some things. Well at any rate I will make sure to give you a copy of everything just in case something goes wrong. I always have your mod in my modpacks so I will definitely be testing the hell out of your mod!

**Comment by DPxKnightxZero** [comment]
Okay; so after a long delay I can say I have a pack built. Here is the information. https://docs.google.com/document/d/1F0oKJpR1eMcafyi0VF2oYD6M0CBRbAEbJgz9iZgxreI/edit?usp=sharing

**Comment by fewizz** [comment]
@DPxKnightxZero . ok, thanks.

**Comment by P3rf3ctXZer0** [comment]
https://github.com/P3rf3ctXZer0/DeathPlagueGaming

**Comment by Ch4imon** [comment]
Hi,
I'm testing your mod too.
At first glance, I might say that there is a conflict with Chisel&bits (and Drawer&bits)

[14:18:03] [Server thread/ERROR] [FML/]: Caught exception from chiselsandbits
java.lang.ExceptionInInitializerError
	at mod.chiselsandbits.core.ChiselsAndBits.clearCache(ChiselsAndBits.java:250) ~[ChiselsAndBits.class:?]
	at mod.chiselsandbits.core.ChiselsAndBits.idsMapped(ChiselsAndBits.java:237) ~[ChiselsAndBits.class:?]

**Comment by P3rf3ctXZer0** [comment]
Okay after getting past 8000 blocks I noticed many weird duplication bugs. I also noticed that the idSort table is getting corrupted at random.

**Comment by P3rf3ctXZer0** [comment]
No more issues as of late
