### ISSUE TITLE
fix id and the name of block?

### ISSUE THREAD

**Issue by SvEgiiVEteR** [fewizz/NotEnoughIDs#34]
не знаю как все на это на английский перевести, по этому только на русском.
проблема такая. на старой карте если обновить какой либо мод или добавить новые.
карта может сломаться.ваш мод в этом не учавствует, но можете ли вы на своей стороне какой нибудь фикс сделать для этого?
по опыту крашей предположу что добавление или обновление мода любого, может вызвать смещение ID при это имя блока не меняться.
вот пару крашей с  модами
https://github.com/McJty/RFTools/issues/330
https://github.com/WayofTime/BloodMagic/issues/568
в последнем как я понял мод BloodMagic считает не которые блоки из ротарикрафт принадлежать ему...ну или наоборот. 
первый раз встретил такую проблему после добавления RFTools
(1 раз получилось зайти на карту с добавленым RFTools и увидел что блоки из тинкера стали полосатые а затем крашь рендера последовал)
или может вы знаете иное решение этой проблемы, может мод кто нибудь сделал для фикса

**Comment by THEVOLCO** [comment]
Do you even english bro?

**Comment by SvEgiiVEteR** [comment]
@THEVOLCO I can't do it all correctly explain in English ((

**Comment by fewizz** [comment]
@SvEgiiVEteR , давно уже смотрел, фиг знает как фиксить :smile:

**Comment by SvEgiiVEteR** [comment]
@fewizz то есть, не я один с тако
