### ISSUE TITLE
NEID & WorldEdit Incompatible

### ISSUE THREAD

**Issue by spannerman79** [fewizz/NotEnoughIDs#35]
NEID: [NotEnoughIDs-1.4.2.jar](http://minecraft.curseforge.com/projects/notenoughids/files/2275080)

WorldEdit: Doesn't matter which one, tested with all of them - latest http://builds.enginehub.org/job/worldedit/last-successful?branch=master

Forge: 1614

If you issue a command that affects a block with an ID greater then 4096 the following happens;

`Can't have a block ID above 4095 (xxxx given)`

`//regen`, `/replace x y` etc doesn't work if within that selection or a block ID is above 4095

Edit: Issue opened also at http://dev.enginehub.org/youtrack/issue/WORLDEDIT-3390

**Comment by fewizz** [comment]
Try this: https://drive.google.com/file/d/0BwY_2FEZWt8dVkJYT1k0S0Z0bVk/view?usp=sharing

**Comment by spannerman79** [comment]
Testing it now (I'm UTC+10) I'll edit this comment with results

**Comment by DPxKnightxZero** [comment]
I am also testing this build. I will let you know if an issue arises.

**Comment by spannerman79** [comment]
Its been 24 hours so far and I have tried every single thing in WorldEdit to test this new update that you provided @fewizz .  Not a single issue.

I've done regen, replacing blocks by id and their actual name - everything - and works without a single issue.

**Comment by DPxKnightxZero** [comment]
Yeah I can confirm this as well; great job on this release. I recommend calling it a stable release.
