### ISSUE TITLE
Crash with NEID 1.4.2

### ISSUE THREAD

**Issue by lightning02** [fewizz/NotEnoughIDs#36]
http://pastebin.com/3yx1JvHw

hello, I'm sorry to bother, I've tryed to add NEID 1.4.2 and it happen to crash with a mod called Monoblocks, in the crash it says the block com.monoblocks.blocks.SteelOre@6c477475 is not registered. I've tryed to update the mod and delete its config file, but the crash seems still occur. What does it mean with "the block is not registered"? is a mistake the author made? is something solvable in any way, even manually fixing it? should I contact monoblocks author?

The first crash happen to the server side, but on the client side the crash is almost the same with the only difference that the modpack starts normally then when you try to create a world it crash with that report

http://pastebin.com/03sNUeAP

**Comment by fewizz** [comment]
Yes, it's monoblocks author's mistake. Try to set RemoveInvalidBlocks to true (in NEID config)

**Comment by lightning02** [comment]
I'm aware that in NEID there is a function that, if enable, removes the corrupted blocks, but.. is this the only way? My question was kinda this one :l

**Comment by fewizz** [comment]
ATM yes, is the only solution. Also, will be good, if you write to author of monoblocks about this issue. :grin:

**Comment by lightning02** [comment]
sure, I will do ^^  btw, is there any link where people can donate to you? I didn't find around :o maybe I didn't look accurately :/  I didn't find any around

**Comment by fewizz** [comment]
@lightning02 , will be better, if you will donate to @sfPlayer1 [profile on ic2 forum] (http://forum.industrial-craft.net/index.php?page=User&userID=49) :relaxed:
