### ISSUE TITLE
Problem with worldedit and block id range

### ISSUE THREAD

**Issue by lightning02** [fewizz/NotEnoughIDs#37]
Hi Guys
I have installed fastcraft c17 and NEID 1.4.3 hoping it wouldn't have generate issues with worldedit.
I noticed that when i go for cutting an area with worldedit on command //cut it says "java.lang.IllegalArgumentException:Can't have a block id above 4095 (9744given)".
At the beginning i have tracked down this issue on DenseOres, in fact removing that mod allowed me to operate on the worldedit-selected-area without this issue but later on the same issue occurred with "copper ore" (id 9448:1) from Electrical Age and at that point i realised the problem was only between worldedit and NEID. Is there something that can be done about this?
Thank you in advace

![7b1918ae-01b1-11e6-9243-0cc9723e8a85](https://cloud.githubusercontent.com/assets/11884147/14507673/0d38d94c-01c4-11e6-84c8-348d5bfaf880.png)

**Comment by fewizz** [comment]
https://github.com/fewizz/NotEnoughIDs/issues/35

**Comment by lightning02** [comment]
I already have that version, it is NEID 1.4.3

**Comment by fewizz** [comment]
ah, ok...

**Comment by Bogdan-G** [comment]
ru; у всех(большинство популярных) плагинов стоит лимит на уровне кода не выше 4095

en: at all (most popular) plugin is code-level limit is not higher than 4095

**Comment by lightning02** [comment]
Yeah.. ;/ i choosed exactly that one hoping it would have worked with world edit.
I should try to quote the problem to the owner of worldedit? do you know if he/they are still active?

**Comment by fewizz** [comment]
No... Please, give me your worldedit mod file.(jar)

**Comment by lightning02** [comment]
https://www.dropbox.com/s/o9atrrk091y4knk/Thermos%20plugins%20folder%20%28only%20world%20edit%20inside%29.zip?dl=0

This is my plugin folder with worldedit file.(jar)

**Comment by fewizz** [comment]
Thanks, i'll look tomorrow :smile:

**Comment by lightning02** [comment]
Thank you! Thanks a lot for the time that you spent and the effort you're putting into this project!

**Comment by fewizz** [comment]
https://drive.google.com/open?id=0BwY_2FEZWt8dV3M2eG95UEVPV0U

**Comment by lightning02** [comment]
![6352c75f69a5720374d703144d9cafab0f779aa3efee2983f2 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/14571060/90cd45e8-0347-11e6-84d3-669d57f43cc9.png)

Same problem :(

**Comment by lightning02** [comment]
I've tryed also to create new world with the version of NEID you gave me, but there is the same problem, there is still some raw mod ore that figure out with an id higer than 4095 and in fact worldedit wont work on those blocks.

**Comment by fewizz** [comment]
"Should i do something other" no, nothing

**Comment by fewizz** [comment]
https://drive.google.com/open?id=0BwY_2FEZWt8dRVJJelBodkVZNHc

**Comment by lightning02** [comment]
Fewizz, let me say this... you are the number one, definetly.
Actually it works without any apparently issue, I really don't know how to thank you!

**Comment by jcettison** [comment]
Can you provide an updated version of WorldEdit with this support? Or can you explain what you changed in this build? (Is it just the blockID limit in the Blocks class? It warns that it only internally supports up to 4095... so I havent tried rebuilding it myself.

**Comment by fewizz** [comment]
@lightning02 , yes, just limit.

**Comment by jcettison** [comment]
Works like a charm, thank you.

If anyone else encounters this problem, you can simply compile WorldEdit yourself, changing the BaseBlock.java in worldedit-core to read "public static final int MAX_ID = 31999;" beforehand.

If you can't be bothered, I've also uploaded the latest Snapshot as of today here: 

[WorldEdit Bukkit 6.1.7 Snapshot NEID Compat](http://repo.deusversus.com/worldedit-bukkit-6.1.7-SNAPSHOT-dist.jar)

**Comment by bradster2214** [comment]
i'm having this problem with minecraft 1.7.10. and there is no "baseblock.java" file in my minecraft folder. 
i have version 6.1.1 of WorldEdit. help!
