### ISSUE TITLE
NotEnoughIDs-1.4.3 server

### ISSUE THREAD

**Issue by SvEgiiVEteR** [fewizz/NotEnoughIDs#39]
https://gist.github.com/74f3e23b669fafc626ff2a071886bd99

**Comment by fewizz** [comment]
А с 1.4.2 работает?

**Comment by fewizz** [comment]
[Sorry](http://minecraft.curseforge.com/projects/notenoughids/files/2299566) for this :disappointed:

**Comment by SvEgiiVEteR** [comment]
спасибо теперь всё ок)
а что делает опция
    #  [default: false]
    B:CatchUnregisteredBlocks=false

**Comment by fewizz** [comment]
теперь незарегистрированные блоки не будут ловиться как это было до этого (пока не включишь CatchUnregisteredBlocks).
