### ISSUE TITLE
Extend potion and enchantment IDs

### ISSUE THREAD

**Issue by DrZed** [fewizz/NotEnoughIDs#4]
Just go ahead and copy my code for those and check Reika's for potion ASM for potion packets to fix client problems... as for biome id's Plz hurry XD
http://github.com/HxCKDMS/HxCCore

**Comment by DrZed** [comment]
http://github.com/HxCKDMS/HxCCore

**Comment by Adaptivity** [comment]
It is planned :smile: @fewizz just busy right now.

**Comment by DrZed** [comment]
@Adaptivity  >_< Are you everywhere?

**Comment by Solarstrike** [comment]
@DrZed You can basically say that.

**Comment by neoneosa** [comment]
also good ieda

**Comment by DPxKnightxZero** [comment]
How do i fix hard-coded mod IDs? Like apparently Ic2 and biomes o plenty are fighting over potion ID's I have never had an issue this unsolvable.

**Comment by Adaptivity** [comment]
http://minecraft.curseforge.com/mc-mods/229978-extended-potions Also, rename .jar to 1ExtendedPotions-MC1.7.10-1.2.jar. This solve loading order issues.

**Comment by DPxKnightxZero** [comment]
Thank you that solved everything!

**Comment by DrZed** [comment]
Just modify the configs? BOP is configurable

**Comment by Adaptivity** [comment]
@DPxKnightxZero try regenerating your configs.
@DrZed BoP potion ids aren't configurable.

**Comment by DrZed** [comment]
@Adaptivity I didn't know that 0_0 hmm..

**Comment by DPxKnightxZero** [comment]
@Adaptivity thanks for the suggestion but I already did all possible basic fixes.
