### ISSUE TITLE
Weird block breaking bug

### ISSUE THREAD

**Issue by THEVOLCO** [fewizz/NotEnoughIDs#40]
Hi,
I'm having trouble with a weird bug that I'm pretty sure is being caused by your awesome mod. Now that I've added like 239 mods to my private pack I'm having following issue:

When I break a block of some mod
* it makes the breaking sound of a diffferent one and
* the "breaking particles" are from the block that would make the sound when you would break it.

For exmaple:

When I break a block X it has the "breaking particles" of block Y and also makes the breaking sound of Y.

Any ideas why this is happening?

**Comment by fewizz** [comment]
Hi, can you gimme your modpack(in zip file(if you can)), please? Thanks.

**Comment by THEVOLCO** [comment]
Yeah, I could but wouldn't it take ages for you waiting for it to finish downloading e.g. from dropbox?

**Comment by fewizz** [comment]
dropbox will be good for me

**Comment by THEVOLCO** [comment]
I'm uploading it atm. In 1 hour I should be able to send u a link.

**Comment by THEVOLCO** [comment]
https://www.dropbox.com/s/ntcpujoc6yorsj4/modPack.rar?dl=0

Break a block from the Nether Ores mod to see what I mean.

**Comment by fewizz** [comment]
Thanks.

**Comment by THEVOLCO** [comment]
It's not finished yet but everything should work.

**Comment by THEVOLCO** [comment]
Btw how much time does it take to dowlnoad it?

**Comment by fewizz** [comment]
I Found the problem. Fixing...

**Comment by THEVOLCO** [comment]
Perfect. Thank you very much.

**Comment by THEVOLCO** [comment]
I dont't want to hurry you but how long is it going to take?

**Comment by fewizz** [comment]
soon release.

**Comment by THEVOLCO** [comment]
Ok thanks :D

**Comment by fewizz** [comment]
http://minecraft.curseforge.com/projects/notenoughids/files/2300284

**Comment by THEVOLCO** [comment]
I dowloaded it. Now everything is working perfectly. Thanks again. Now I can go on with adding mods to my private pack like a lunatic xD.

**Comment by fewizz** [comment]
Good luck! :smile:
