### ISSUE TITLE
NotEnoughIDs-1.4.3.2

### ISSUE THREAD

**Issue by SvEgiiVEteR** [fewizz/NotEnoughIDs#41]
поймал проблему в одиночном мире, создаю карту и выкидывает в меню((
https://gist.github.com/56ec814d20b3c6a6951b0e0a7ee7b42c

**Comment by fewizz** [comment]
Возможно проблемки с драгонапи. А 1.4.3/1.4.3.1 работают?

**Comment by SvEgiiVEteR** [comment]
143 с поддержкой вор едита точно пашет шас проверю 1431

**Comment by SvEgiiVEteR** [comment]
1431 тоже крашит

**Comment by SvEgiiVEteR** [comment]
проверить смогу тока вечером. если что

**Comment by fewizz** [comment]
Кидай сюда свой супер тяжеловесный модпак :smile:

**Comment by SvEgiiVEteR** [comment]
да тяжёлый) но с ошибкой столкнулься с такими модами:
0EXT_0_NotEnoughIDs-1.4.3.2.jar1
0EXT_LIB_RM_DragonAPI 1.7.10 V13b.jar
0EXT_LIB_zExtendedPotions-MC1.7.10-1.2.jar
2_1_industrialcraft-2-2.2.821-experimental.jar
2_3_Mekanism-1.7.10-8.1.9.266.jar1
2_3_Mekanism-1.7.10-8.1.9.267.jar
2_3_MekanismGenerators-1.7.10-8.1.9.266.jar1
2_3_MekanismGenerators-1.7.10-8.1.9.267.jar
2_3_MekanismTools-1.7.10-8.1.9.266.jar1
2_3_MekanismTools-1.7.10-8.1.9.267.jar
2_FSP-1.7.10-0.29.2.jar
10_UniDict-1.7.10-1.7d.jar
INFO_GUI_2_S_EnderCore-1.7.10-0.2.0.34_beta.jar
INFO_GUI_2_S_Waila-1.5.10_1.7.10.jar
INFO_GUI_2_S_WailaHarvestability-mc1.7.10-1.1.6.jar
INFO_GUI_2_S_WAILAPlugins-MC1.7.10-0.2.0-23.jar
INFO_GUI_3_S_NEIIntegration-MC1.7.10-1.1.2.jar
INFO_GUI_3_S_NotEnoughItems-1.7.10-1.0.5.120-universal.jar
INFO_GUI_3_S_NotEnoughResources-1.7.10-0.1.0-122.jar

хотел UniDict-1.7.10-1.7d.jar по глядеть как работает)

**Comment by SvEgiiVEteR** [comment]
нашёл....
0EXT_0_NotEnoughIDs-1.4.3.2.jar
2_1_industrialcraft-2-2.2.821-experimental.jar
2_3_Mekanism-1.7.10-8.1.9.267.jar
в такой связке кидает из мира
https://gist.github.com/6b9da45cf6e58f76d10a7bf8d066c3d6

**Comment by fewizz** [comment]
1) крашлог неполный
2) желательно весь список модов
3) будет лучше если просто скинешь модпак(только папку mods и config)

**Comment by SvEgiiVEteR** [comment]
1) краш лога нет толко лог. я создаю карту и меня выкидывает в меню игры сама игра не закрываеться. захожу повторно на карту опять выкидывает.
а если лог обрезанный то вот
https://gist.githubusercontent.com/SvEgiiVEteR/6b9da45cf6e58f76d10a7bf8d066c3d6/raw/aa93c5182a3505548e3bfa188fc5f0f554147500/2016-05-16_20-07-04.txt
там кнопочка есть что бы его открыть полностью.)))
2)
папка 1710
1CodeChickenCore-1.7.10-1.0.7.47-universal.jar
[1.7.10]bspkrsCore-universal-6.16.jar
CodeChickenLib-1.7.10-1.1.3.140-universal.jar
ForgeMultipart-1.7.10-1.1.2.331-universal.jar
папка модс
0EXT_0_NotEnoughIDs-1.4.3.2.jar
2_1_industrialcraft-2-2.2.821-experimental.jar
2_3_Mekanism-1.7.10-8.1.9.267.jar
и всё
3) могу щас кинуть))

**Comment by fewizz** [comment]
расширение идишек датаватчера включено?

**Comment by SvEgiiVEteR** [comment]
да включено...пак кинул выше

**Comment by fewizz** [comment]
Спасиб :smile:

**Comment by SvEgiiVEteR** [comment]
ну что проблема имет место быть?а то боюсь вдруг ещё какой мод вызовет.кроме меканизма..

**Comment by fewizz** [comment]
Обнулил конфиги, врубил увеличение лимита, не вылетает...

**Comment by SvEgiiVEteR** [comment]
спс..щас буду искать в каком конфиге косяк. не думал что что так...

**Comment by SvEgiiVEteR** [comment]
похоже дело в multipart.cfg
в этих опциях..
http://i.imgur.com/ctAOWEL.png
которые в конфиге моём.

**Comment by fewizz** [comment]
Время [тестов](https://drive.google.com/file/d/0BwY_2FEZWt8dMXJZS1g1Wk9NNTQ/view?usp=sharing)

**Comment by SvEgiiVEteR** [comment]
@fewizz пока всё хорошо,но надо по тестить денёк..)спасибо)

**Comment by fewizz** [comment]
Косяк, причем очень глупый...

**Comment by SvEgiiVEteR** [comment]
@fewizz рад что помог найти..странно что тока я 1 написал ..буд то только я и использую мод..
