### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by lightning02** [fewizz/NotEnoughIDs#42]
Hi fewizz, how are you going?
I recently noticed a strange behavior ; when i break a block with an id higher than 4096 the micro-textures appear to look like something different from that block, like if you was breaking a totally different block.
Here are some example:  
![d1fa622f368d9c7ae61e67fffc1e9274bcc1041282eab43625 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/15399651/d55356ce-1de8-11e6-9d70-5c92e9a4755f.png)
![1](https://cloud.githubusercontent.com/assets/11884147/15399700/ff18feaa-1de8-11e6-8bba-0f215a885b5b.png)
![0fa6b09806f0ed5b8de15478858c9221dca121f0c88625bd1b pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/15399722/0e6802e8-1de9-11e6-8ccb-0fc4ad5e0e0f.png)

I don't know if there is something that can be done to fix this, like a client side visual fix; btw this is not fortunately a really bad issue.
I'm still using the last version of neid 1.4.3 that you gave me.

**Comment by fewizz** [comment]
download latest version from [curse](http://minecraft.curseforge.com/projects/notenoughids/files/2300687)

**Comment by lightning02** [comment]
Is that still compatible with worldedit?

**Comment by fewizz** [comment]
should
