### ISSUE TITLE
Crash with 1.4.3.3

### ISSUE THREAD

**Issue by Keyarose** [fewizz/NotEnoughIDs#43]
Upgraded from 1.4.2 to 1.4.3.3 and crashed during startup.  Same set of mods aside from NEIDs. Downgraded back to 1.4.2 and everything works once more.

Crashlog: http://pastebin.com/DBwjg57E

Modlist(NEI Integration dump): https://docs.google.com/spreadsheets/d/1KE1b74hJ0N73zbH9Cmhut-KcH5Qz5fHqevSB7qipf2M/edit?usp=sharing

**Comment by Keyarose** [comment]
Just tested 1.4.3.2 and the crash does not happen.

**Comment by fewizz** [comment]
Seems like 1.4.3.3 just not loaded. O_o

**Comment by fewizz** [comment]
Pls, redownload 1.4.3.3 again...

**Comment by Keyarose** [comment]
Really weird, it works now.  I originally downloaded through the curse client, this time I downloaded directly from the curseforge page.  Thanks for the help, and for the great mod.
