### ISSUE TITLE
Crash on initialization

### ISSUE THREAD

**Issue by vrork** [fewizz/NotEnoughIDs#46]
Log: http://pastebin.com/a8bXN5eT

Your mod is the last one before the errors, so i suspect it is related. (look at line 32)

**Comment by fewizz** [comment]
No, from 13 - 28 same warnings.

**Comment by vrork** [comment]
Suggestion on what it could be? I tried reinstalling minecraft with no luck and i didnt add any new mods since last time i played

**Comment by P3rf3ctXZer0** [comment]
Its not, not enough Ids XD

**Comment by vrork** [comment]
@P3rf3ctXZer0 Here are all the logs. Get ready, they are massive.
https://gist.github.com/vrork/c4dd3ada1d8622cf98daf32a8b8ad79b

Ah, its not Flat Colered Blocks, tried disabling with no luck

**Comment by P3rf3ctXZer0** [comment]
So far; Chisels looks like the culprit! - https://gist.github.com/P3rf3ctXZer0/ecafec70ce1c89f561d9f952fe9d24d8

**Comment by P3rf3ctXZer0** [comment]
Can I have a copy of your modpack? Please export via MultiMc https://multimc.org

**Comment by vrork** [comment]
@P3rf3ctXZer0 its Not Chisels. 
I dont know how to use MultiMC

**Comment by P3rf3ctXZer0** [comment]
@vrork its super rude if you don't attempt to solve your own problems. Anyways here is a youtube tutorial.

https://www.youtube.com/watch?v=Uv_n61IaGCc

next time google how to use it or select the faq page

https://discordapp.com/invite/0k2zsXGNHs0fE4Wm

**Comment by vrork** [comment]
@P3rf3ctXZer0, well, on the same way you want me to use MultiMC, i could ask you to use Curse Launcher.
But its not needed anymore, mods updated and it fixed, not sure wich one was the one causing that tough,
