### ISSUE TITLE
strange bug with TAIGA ores

### ISSUE THREAD

**Issue by Hypsellis** [fewizz/NotEnoughIDs#47]
I link this issue because notenoughid could be the cause of this issue https://github.com/Zkaface/TAIGA/issues/56

**Comment by P3rf3ctXZer0** [comment]
Not likely.

**Comment by fewizz** [comment]
@Hypsellis , gimme pls your "mods" and "configs" folder + corrupted world save. Thanks.

**Comment by Hypsellis** [comment]
Here you have the mod and config list, you can create any world and reload it after, the bug will happen at each time. https://drive.google.com/file/d/0B3qgq_iexVeDMGxCdUQ4QXVhT2M/view

**Comment by fewizz** [comment]
@Hypsellis , i returned home and tried to test your modpack (sorry for waitig), but i have only 8GB memory =_= . Soon (™) i'll give special version of NEID for debugging this problem.

**Comment by Hypsellis** [comment]
Oh yeah don't try it if you have only 8GB of memory, I have 32GB and use 16GB for being able to play to my modpack. ^^'

**Comment by P3rf3ctXZer0** [comment]
I can test it fewizz what am I looking for?

**Comment by Hypsellis** [comment]
You didn't even look what we talk about since the beginning of this issue, the taiga ores that get replaced after a world reloading, you even didn't reload the world.
I suppose you didn't take the config folder too for having the better sleeping and goethia gui at these places.
I will make a small video for showing the bug tonight when I will be at home.

**Comment by fewizz** [comment]
@P3rf3ctXZer0 , thanks, indeed. @Hypsellis , try (this)[https://drive.google.com/file/d/0BwY_2FEZWt8ddEdrNm5JSGpSUFU/view?usp=sharing]

**Comment by Hypsellis** [comment]
It seems that the problem doesn't happen more. Thanks so much for having corrected it. ^^
Eh you should maybe release the new NEI version on Curse. ;)
Anyway for the time I close this issue.

**Comment by fewizz** [comment]
OC
