### ISSUE TITLE
Compatibility with Sponge 1.10.2

### ISSUE THREAD

**Issue by kokomo616** [fewizz/NotEnoughIDs#49]
Would It be possible to add compatibility With SpongeForge 1.10.2 (server side) It seems to crash I tried posting the log but Github says its to long (I might be doing something wrong I'm new to github please forgive me). It does not give me a actual crash report.

**Comment by fewizz** [comment]
I'll take a look

**Comment by fewizz** [comment]
@kokomo616 , (fixed)[https://minecraft.curseforge.com/projects/notenoughids/files/2366220]
