### ISSUE TITLE
Seems to cause graphics lag in third-person mode and with Bibliocraft armor stands

### ISSUE THREAD

**Issue by gjsmo** [fewizz/NotEnoughIDs#50]
This is a very weird issue which I am having trouble nailing down. A few things i've tried are shown [here](https://www.reddit.com/r/feedthebeast/comments/5lomic/why_is_my_armor_stand_dropping_me_to_23fps/), but the gist of the issue is that I'm currently trying to update the mods to an only 1.7.10 world and I'm running into ID limits. Adding NotEnoughIDs seems to solve the problem, but after this there are issues after adding mods which were previously causing ID issues.

Specifically, upon adding new mods while using NotEnoughIDs, when in third-person mod or viewing armor stands with non-standard models, such as Terrasteel or Power Armor, I drop to 2-3FPS and the game is basically unplayable. This doesn't happen with just NotEnoughIDs installed. I have Optifine installed, which is the only global graphics mod I can think of that might be related.

Where do I start to find an issue like this? Initially, per the Reddit thread, I though the problem was MineChem as the issue only occurred after updating that - however I have now noticed that upon updating Metallurgy the same issue occurs, which seems to indicate that it's not related to those mods. I can provide any data needed but I have no idea where to begin.

**Comment by fewizz** [comment]
@gjsmo , idk why this happens(
