### ISSUE TITLE
[1.10.2] WorldEdit and NotEnoughIDs?

### ISSUE THREAD

**Issue by DeadSix27** [fewizz/NotEnoughIDs#51]
Looked through the issues saw some patched builds for WorldEdit and NEI both are too old tho or for Sponge or so. 

What exactly do I have to to be able to work-around the blockID issue?

```
Caused by: java.lang.IllegalArgumentException: Can't have a block ID above 4095 (4542 given)
        at com.sk89q.worldedit.blocks.BaseBlock.internalSetId(BaseBlock.java:145)
```

## EDIT:
Patched WorldEdit myself: [world_edit_1_10_2_block_id_range.patch](https://gist.github.com/DeadSix27/0c877fbc343bf7d7b0333e402c527b7d) 

I also have the binaries(jars) compiled for people that need it:

https://files.dsix.tech/binaries/java/minecraft/1.10.2/worldedit/

Seems to work just fine so far. No issues (yet)

**Comment by P3rf3ctXZer0** [comment]
@DeadSix27 can you fix world edit so it works in SP again for mapmakers?

**Comment by DeadSix27** [comment]
@P3rf3ctXZer0 Not sure, all I did was increase the blockID limit in WE, whats not working in SP?

**Comment by P3rf3ctXZer0** [comment]
@DeadSix27 the Vanilla world edit didn't work with single player; yours does however thank you for that.

**Comment by fewizz** [comment]
1.5.3
