### ISSUE TITLE
Crash with certain ids and metadata

### ISSUE THREAD

**Issue by RebelKeithy** [fewizz/NotEnoughIDs#52]
**Issue Description:**
I'm playing the MMD modpack and when every you harvest a fully grown draconium plant the client crashes (blockid=12480). After doing some testing I noticed the ids seem to wrap around. The copper plant (blockid=12451) has no sound or particles. The next plant (blockid=12452) has stone particles, etc. So when it thinks draconium is a piston it tries to get a pistons blockstate with meta = 7, the pistons getfacing then return null and causes the crash.

**Crashlog:**
http://pastebin.com/cQkB2jFx
(This is the crashlog after removing FoamFix from the pack.)

**Versions:**
Minecraft: 1.10.2
NotEnoughIDs: 1.5.2
Forge: 12.18.3.2209

**Comment by P3rf3ctXZer0** [comment]
@RebelKeithy update forge to 221

**Comment by RebelKeithy** [comment]
Updated to forge 2221, still have the same problem

**Comment by RebelKeithy** [comment]
By the way, I'm fairly certain this is cause in the RenderGlobal.playEvent event method, case type=2001 there is a line "Block block = Block.getBlockById(data & 4095);" It looks like you aren't replacing that 4095.

**Comment by fewizz** [comment]
@RebelKeithy , you are right =_= . (Test build)[https://drive.google.com/file/d/0BwY_2FEZWt8dMS1QZ0RLZWZCZ3M/view?usp=sharing]

**Comment by RebelKeithy** [comment]
That fixed it.
