### ISSUE TITLE
Crashing 1.7.10 Please help

### ISSUE THREAD

**Issue by Gamerbolts** [fewizz/NotEnoughIDs#53]
I am not sure what is causing this. But I have a big modpack. So needed NotEnoughIDs. Things were working fine, added Lookingglass to get the extra features. 

Whenever I right clicked to connect the camera it crashed my client. Took out every mod except Securitycraft, Lookingglass, and NotenoughIDs. 

Tried right clicking and was met with this http://imgur.com/a/sYoQO. Can't move can't do anything. Just sitting there. This is the log. http://pastebin.com/S83DYPxD 

I apologize that it is not complete. Pastebin didn't let me paste the full one. 

I have posted this on Securitycraft, Lookingglass and NotEnoughIDs githubs. 

Anyone please help!

Thank you.

**Comment by Gamerbolts** [comment]
Update
-Securitycraft and lookingglass work fine by themselves. It's only when I added NotEnoughIDs and tried that it does what the image shows. I have tried v1.4.3.4 v1.4.3.3 and v1.4.3.2 all with the same issue. Not too sure what is going on. please help

**Comment by fewizz** [comment]
@Gamerbolts , incompatibility between neid and lookingglass.

**Comment by Gamerbolts** [comment]
The author of NEID said he would look into it. Is there anything you can do on your side?

**Comment by Gamerbolts** [comment]
Is there anything that can be done about this incompatibility on your side?

**Comment by Gamerbolts** [comment]
Please is there anything that can be done about this issue? It's for 1.7.10 it's definitely an incompatibility between neids and looking glass. Author of looking glass is looking at it. Can you do anything about it? Please

**Comment by Gamerbolts** [comment]
Hey, have you looked into this at all? Is there anything that you can do? I have spoken with the mod authors for Securitycraft and Lookingglass, they have been trying to help, but it is on your mods end... so there is not much they can do, please help

**Comment by fewizz** [comment]
[not now](https://en.m.wikipedia.org/wiki/Unified_State_Exam)
