### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 4529

### ISSUE THREAD

**Issue by Heyyo53** [fewizz/NotEnoughIDs#54]
Not 100% sure this is caused by this mod, but I feel like its something todo with it. It happens whenever I try to make a world or load new chunks

Edit: I'm guessing its a incompatibility with The Terrain control mod :/

heres the crash report
[http://pastebin.com/nYJk0i80](url)

**Comment by fewizz** [comment]
![image](https://cloud.githubusercontent.com/assets/8060034/23580850/74918cb4-011a-11e7-8f0c-ea0fc88f3375.png)

**Comment by fewizz** [comment]
1.10 isn't supported.
