### ISSUE TITLE
We are here again; Can you make a port of 1.11.2?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [fewizz/NotEnoughIDs#56]
So I am now using 1.11.2 care to help making an id limit increase?

**Comment by fewizz** [comment]
@P3rf3ctXZer0 , okey

**Comment by P3rf3ctXZer0** [comment]
Glad I can count on you @fewizz let me know when a test release is up ;)

**Comment by fewizz** [comment]
https://drive.google.com/file/d/0BwY_2FEZWt8dLWh0VzFvUVZYWkk/view?usp=sharing

**Comment by P3rf3ctXZer0** [comment]
Package received; I will let you know the results in no less than 8 hours.

**Comment by P3rf3ctXZer0** [comment]
Alright 8 hours of testing no bugs that I have noticed. I will let you know if that changes.
