### ISSUE TITLE
NotEnoughIDs

### ISSUE THREAD

**Issue by aGreenCrystal** [fewizz/NotEnoughIDs#57]
I just created a modpack with about 500 mods, and it needs more possible ids. 36000 is not enough! 😋 
I don't know if it is hard for you to raise the limit even higher, but as you already coded the mod, i guessed that it isn't. If it'd be possible i'd be very happy if there'd be like a config file in which you can say on your own where the limit should be.
I don't know if it'd be possible, but I would be very happy if it would be 😃 

- aGreenCrystal

**Comment by sfPlayer1** [comment]
Seriously? Some mod must be spamming items or blocks. Any idea which mod it is?

**Comment by aGreenCrystal** [comment]
Yes I already know it is the mod called "BlockArmor" which creates a full set of armor for every block ingame (also for mod blocks), so it spams IDs really bad.

**Comment by fewizz** [comment]
Try (this)[https://drive.google.com/file/d/0BwY_2FEZWt8dRVdYYTdabUViQWM/view?usp=sharing] (if you playing on 1.10)

**Comment by aGreenCrystal** [comment]
what is that

**Comment by fewizz** [comment]
@aGreenCrystal , version with item id ext.
