### ISSUE TITLE
Entity issue

### ISSUE THREAD

**Issue by Solarstrike** [fewizz/NotEnoughIDs#6]
From the test build of NEIDs (the first of many array issues):
http://pastebin.com/G9V0NSPe

**Comment by fewizz** [comment]
full log pls.

**Comment by Solarstrike** [comment]
That's the report...
unless you're saying the entire forgelog...

**Comment by Solarstrike** [comment]
Weird, it's working now after I started a new world.

**Comment by Solarstrike** [comment]
More explained in #7
