### ISSUE TITLE
entity and biome id extension needed!

### ISSUE THREAD

**Issue by jurassicjordan** [fewizz/NotEnoughIDs#64]
this mod is great for block ID's and stuff but there are more mods that add entities, mobs and biomes. For example Æther mod, Hardcore Ender expansion, Mo' Creature, Ore Spawn, Inferno's Nether Expansion, Flans, Astromech Droids Mod, Custom NPCs, Legendary Beasts, Dalek Mod, Creepy pastas, Creeps and weirdo's, Mutant Creatures, etc. PLEEEAASE add, at the very least, entity IDs, and biome ids if you can. Thank you

**Comment by ErickThePresident** [comment]
support

**Comment by taramul** [comment]
Support. Would be willing to contribute, too.

**Comment by fewizz** [comment]
isn't JEID supports that already?
