### ISSUE TITLE
The biggest issue with the mod

### ISSUE THREAD

**Issue by EmosewaGamer** [fewizz/NotEnoughIDs#67]
While I understand that this will require many changes the way the mod works as a whole, it's an issue that has to be addressed.

 The problem is that, whenever a mod is removed or just blocks from a certain mod are removed, in the world they're replaced by different blocks. On a smaller scale, this could lead to players having blocks that they shouldn't have, but on a larger scale, like when the mod is removed, it can lead to world corruption, to where every modded block is replaced by another modded block.

 The latter happened to everyone playing my pack, when I ported it to 1.12.1. Sure, I understand that the mod wasn't functional on 1.12.1 then, but what if someone just decides to remove this mod from their mod pack?

 Lex and cpw themselves said that it's a bad core mod, so unless this is fixed, if it can be fixed, I will listen to them:
https://twitter.com/voxcpw/status/896840720769839105
https://twitter.com/LexManos/status/896832589381619712

**Comment by P3rf3ctXZer0** [comment]
Well @LexManos was told by me and many other community members the smartest way to fix it is to make it NATIVE in forge! They REFUSE to listen even when me and others have stated time and time again to fix it. At any rate a quick fix is to export structures once a week using recurrent complex!

**Comment by fewizz** [comment]
@EmosewaGamer neid saves additional chunk's data. It isn't pssible to fix. =P

**Comment by fewizz** [comment]
@EmosewaGamer not fixable. Will add a notice to desc about this issue.
