### ISSUE TITLE
Update to 1.12.2

### ISSUE THREAD

**Issue by EmosewaGamer** [fewizz/NotEnoughIDs#68]
Since it's a gamechanging coremod, I already knew that it wouldn't work on 1.12.2, so could you please update to it?

**Comment by P3rf3ctXZer0** [comment]
@fewizz I went out of my way to test your awesome mod but this was the result 
https://gist.github.com/P3rf3ctXZer0/e8022d752e04a459b33cda78bbaf4ab0

**Comment by fewizz** [comment]
https://minecraft.curseforge.com/projects/notenoughids/files/2483497

**Comment by fewizz** [comment]
=P https://minecraft.curseforge.com/projects/notenoughids/files/2483500
