### ISSUE TITLE
Conflict With Better With Mods, Mod

### ISSUE THREAD

**Issue by mysteryblock** [fewizz/NotEnoughIDs#69]
I play with a relatively large collection of mods and have come up against the item limit. Better with mods was working before installing the notenoughides mod to get past this limit, but with this mod installed the soulforged steal anvil's GUI will not pop up.

Minecraft 1.12.2
Forge .2528
Better With Mods 2.0.14
Notenoughids 1.5.4.2

I've also reached out to that mod maker and see if it's an issue on their end.

**Comment by fewizz** [comment]
"Extends ID limit for items to 65534"(From neid desc.)
You can disable this in neid confing

**Comment by mysteryblock** [comment]
The nedi config file does not show up in the minecraft config folder for me.

**Comment by fewizz** [comment]
@mysteryblock ah eah, i hadn't introduced it in new versions =P

**Comment by MainFreak** [comment]
I can not replicate this issue. (However I had other miscelaneous and known issues so I am not going to report them).
