### ISSUE TITLE
Possible Performance Issues

### ISSUE THREAD

**Issue by merjilin** [fewizz/NotEnoughIDs#71]
Greetings, fewizz!

We are currently running an FTB Revelation server (1.8.0) which uses version 1.5.4.2 of NotEnoughIDs and we're encountering a few issues which we think may require your input.

Recently, we have been experiencing a lot of stalls which we are having trouble narrowing down for the main part. However, thanks to a sampling tool we're able to capture a profile of what is being executed during the lag spike. Whilst looking through some of these profile samples, we have found the following entry multiple times, all of which have been high in terms of percentage on the Server Thread.

![image](https://user-images.githubusercontent.com/24194378/39154621-d1f31f08-4746-11e8-85c9-68e20a05fcf7.png)

We were wondering whether there is anything that can be done on this end to help smooth this out, as we're completely out of ideas with regards to what may be causing the issue. 

Thank you for your time, merjilin :)

**Comment by fewizz** [comment]
Try [this](https://drive.google.com/file/d/16eJwJX-b12FgDsRQtcQcD89pFcUwW6uY/view?usp=sharing)

**Comment by fewizz** [comment]
[2nd ver.](https://drive.google.com/file/d/196VrmTtl1JfRJC1Hhq6Jb_ZbAqVAxeQs/view?usp=sharing)

**Comment by fewizz** [comment]
[3rd](https://drive.google.com/open?id=11LFNv8MTyGJ6G3eRViXlDdemHEXQhbj3)

**Comment by P3rf3ctXZer0** [comment]
Oh my God someone figured out what I could not :D Thank you @merjilin I too will test @fewizz

**Comment by fewizz** [comment]
Nobody commented about how these versions works, so i thought that these versions not fixed problem.

**Comment by esotericist** [comment]
I'll see if I can't arrange for some testing.
