### ISSUE TITLE
[SUGGESTION] Extend potion IDs to 4096

### ISSUE THREAD

**Issue by Sunconure11** [fewizz/NotEnoughIDs#72]
On earlier versions of MC, there used to be mods that would let you extend potion IDs. With more and more mods cropping onto 1.12.2, would it be possible to add such support to this mod?

**Comment by matyklugDebbuged** [comment]
i see somewhere it is possible with asm

**Comment by zabi94** [comment]
(Somewhere being [here](https://minecraft.curseforge.com/projects/extra-alchemy?comment=180))

It is possible, You can just add a new field in the packet containing the real ID as a short or int, and then bypass the getter or the instruction fetching the byte everytime it is used to get the integer instead, but that's just an _horribly_ convoluted and hacky solution.
There's a bunch of `someInt & 0xFF` instruction that needs to be removed as well, scattered around the potion handling code, I've seen it in the `EntityPlayerMP` class, but I'm almost positive there are other instances around.

**Comment by fewizz** [comment]
Use [JEID](https://www.curseforge.com/minecraft/mc-mods/jeid)
