### ISSUE TITLE
Crash with the renderer - Only mod that changes the class that crashed is [neid]

### ISSUE THREAD

**Issue by zackeezy** [fewizz/NotEnoughIDs#73]
https://pastebin.com/8WWpRa5A <-- crash log

I looked and the crash log says:

>java.lang.VerifyError: Inconsistent stackmap frames at branch target 914
>Exception Details:
>  Location:
>    
>net/minecraft/client/renderer/RenderGlobal.func_174970_a(Lnet/minecraft/entity/Entity;DLnet/minecraft/client/renderer/culling/ICamera;IZ)V \@905: ifle

And the only mod that changes RenderGlobal is:

>[15:38:49] [main/INFO] [neid]: Patching class: "net.minecraft.client.renderer.RenderGlobal" with Transformer Group: "TransformerGroupBlockHardcoredConstants"

I have been working on this for three days and have tried removing tons of mods with error messages in the log, but I can't get rid of NotEnoughID's because it fixed one of the crashes I had before: namely an out of index exception from too many items.  If I remove neid and try to test it, it'll just crash again.  I'm not sure how to test if your mod is causing a problem, but I hope that you can help.

**Comment by P3rf3ctXZer0** [comment]
First try this on recommended forge and remove all mods that do not play nicely on recommended forge also add this mod for more crash details. https://minecraft.curseforge.com/projects/vanillafix @zackeezy so far I see nothing directly saying NotEnoughIds is the culprit.

**Comment by zackeezy** [comment]
Yea I did some removing of mods meticulously and found out what the issue was.  I was running an outdated version of Advanced Rocketry.  The logs could not tell me that as the crash was happening outside the context of stitching the mods together.  I found this out some time yesterday and meant to update my issue.  You can close it, I was grasping for straws here.

**Comment by P3rf3ctXZer0** [comment]
To be quite honest I have had many problems with advanced rocketry.

**Comment by P3rf3ctXZer0** [comment]
That is why I told you to use vanilla fix.

**Comment by zackeezy** [comment]
I tried updating and downgrading forge.  And searching for my error message didn't help either.  But the recommended forge was too low for Twilight forest, so I was not sure what to do from there short of removing mods one by one, which I ended up doing.

**Comment by P3rf3ctXZer0** [comment]
Honestly I recommend Futurepack https://minecraft.curseforge.com/projects/futurepack/files or Galacticraft https://micdoodle8.com/mods/galacticraft/downloads

**Comment by zackeezy** [comment]
Wait, Galacticraft has a 1.12.2 version out?

**Comment by P3rf3ctXZer0** [comment]
Correct

**Comment by zackeezy** [comment]
I had not seen that it was updated.  I guess I'll replace advanced rocketry when I get back home
