### ISSUE TITLE
Handshake Error possibly caused by NEID (as of Forge Dev) in Forge versions higher than 2655

### ISSUE THREAD

**Issue by D3nnis3n** [fewizz/NotEnoughIDs#74]
Please see this thread: http://www.minecraftforge.net/forum/topic/64580-handshakemessagehandler-error-on-join/

**Comment by P3rf3ctXZer0** [comment]
Loaded coremods (and transformers): 

BetterFontsCore ([C]-TrueTypeFontReplacement-1.9.1.jar)
  cubex2.ttfr.BFClassTransformer
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
SSLoadingPlugin (SereneSeasons-1.12.2-1.2.2-universal.jar)
  sereneseasons.asm.transformer.EntityRendererTransformer
  sereneseasons.asm.transformer.WorldTransformer
LoadingPlugin (Reskillable-1.12.2-1.5.1.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
SignPictureCorePlugin ([C]-SignPicture-2.8.1.jar)
  com.kamesuta.mc.signpic.asm.SignPictureTransformer
DynamicSurroundingsCore ([T]-DynamicSurroundings-3.4.9.13.jar)
  org.blockartistry.DynSurround.asm.Transformer
MMFMLCorePlugin ([CS]-MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
CorePlugin (SmoothFont-1.12.2-1.15.jar)
  bre.smoothfont.asm.Transformer
AppleCore ([T]-AppleCore-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
Plugin ([CS]-NotEnoughIDs-1.5.4.2.jar)
  ru.fewizz.neid.asm.Transformer
CorePlugin ([CS]-ForgeEndertech-4.3.5.0.jar)
  
HammerCoreCore (HammerCore-1.12.2-1.9.9.4.jar)
  com.pengu.hammercore.asm.HammerCoreTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  shetiphian.asm.ClassTransformer
ISCore (ImprovableSkills_1.12.2-3.4.1r.jar)
  com.endie.is.asm.ImprovableSkillsTransformer
BetterFoliageLoader ([C]-BetterFoliage-2.1.10.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
ForgelinPlugin (Forgelin-1.6.0.jar)
  
IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
weaponlib (mw-1.11.7.1_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
LoadingPlugin ([CS]-AdChimneys-3.3.0.0.jar)
  com.endertech.minecraft.mods.adchimneys.world.WorldData$BlockRandomTick
EnderCorePlugin ([CS]-EnderCore-0.5.22.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
EcomodLoadingPlugin (EcologyMod-1.12.2-1.5.1.0.jar)
  ecomod.asm.EcomodClassTransformer
MalisisCorePlugin ([T]-MalisisCore-6.4.0.jar)

Remove this

weaponlib (mw-1.11.7.1_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer

LexManos has a hate boner for @fewizz and vic was already warned this was an issue but refused to fix it.

**Comment by P3rf3ctXZer0** [comment]
Lex is right about one thing though one of the following is the issue

TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
li.cil.oc.common.asm.ClassTransformer

weaponlib (mw-1.11.7.1_mc1.12.2.jar)
com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer

BetterFontsCore ([C]-TrueTypeFontReplacement-1.9.1.jar)
cubex2.ttfr.BFClassTransformer

MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)

EcomodLoadingPlugin (EcologyMod-1.12.2-1.5.1.0.jar)
ecomod.asm.EcomodClassTransformer

ISCore (ImprovableSkills_1.12.2-3.4.1r.jar)
com.endie.is.asm.ImprovableSkillsTransformer

DynamicSurroundingsCore ([T]-DynamicSurroundings-3.4.9.13.jar)
org.blockartistry.DynSurround.asm.Transformer


BetterFoliageLoader ([C]-BetterFoliage-2.1.10.jar)
mods.betterfoliage.loader.BetterFoliageTransformer

IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
blusunrize.immersiveengineering.common.asm.IEClassTransformer

SignPictureCorePlugin ([C]-SignPicture-2.8.1.jar)
com.kamesuta.mc.signpic.asm.SignPictureTransformer <- Switch to Online Pictures by Team CreativeMD

**Comment by P3rf3ctXZer0** [comment]
The ones are listed are not necessarily the cause. Execpt Vics as it plays nice with nothing.

**Comment by D3nnis3n** [comment]
That issue is not caused by NEID. It's caused by Level Up. Therefore i close the issue.

**Comment by fewizz** [comment]
@P3rf3ctXZer0 , thx.
