### ISSUE TITLE
[SUGGESTION] More Biome ID's

### ISSUE THREAD

**Issue by PulseBeat02** [fewizz/NotEnoughIDs#76]
Note: This may be a question that has been asked a couple years ago, but nobody really responded with an answer. I also have downloaded JEID, but it still didn't work.

So basically, what I want you to add to this mod is more biome ID's. I keep getting an error saying that the biome numbers reached ID 256 and can't exceed anymore. Even though I have heard in 1.13, ID's will be removed, my modpack version 1.12.2, and can't support later versions. 

I hope this suggestion could be added soon.

**Comment by fewizz** [comment]
Use [JEID](https://www.curseforge.com/minecraft/mc-mods/jeid)
