### ISSUE TITLE
(Suggestion) Can you add mob ID's?

### ISSUE THREAD

**Issue by ghost** [fewizz/NotEnoughIDs#77]
Many people know this: OreSpawn and another big mod do not go together. Can you fix that problem by adding a increased ID limit?

The game crashed whilst initializing game
Error: java.lang.RuntimeException: No more entity indicies left

**Comment by P3rf3ctXZer0** [comment]
Use Justenoughids

**Comment by TheTank18** [comment]
Forgot to say this: I use 1.7.10.
Sorry for the inconvenience.
