### ISSUE TITLE
Extend biome IDs

### ISSUE THREAD

**Issue by Adaptivity** [fewizz/NotEnoughIDs#8]
Mods to support (Priority: higher in list = higher priority):
- [ ] Realistic Terrain Generation (Crash on startup if biome ids higher than 256)
- [ ] Enhanced Biomes (Crash on world creation, seems to be biome id check)
- [ ] Alternate Terrain Generation (Can't create world, biome id check)
- [ ] ChromatiCraft (Biome id check, crash on startup)

Supported Mods:
- Biomes O Plenty (Biome id check, support on NEID side)
- Extrabiomes XL (No support required, no biome id check)
- Thaumcraft (No support required, no biome id check)
- Highlands (No support required, no biome id check)
- Ridiculous World (No support required, no biome id check)

_Probably_ won't be supported:
Any mod which adds own dimension and biomes to it. Because if you have ids higher 127 for these mods, their biomes then _may_ spawn in overworld. These things are really derpy sometimes...

**Comment by neoneosa** [comment]
Would be cool

**Comment by DPxKnightxZero** [comment]
Sobs* I hit the biome limit 

:( ---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 9/13/15 8:21 AM
Description: Initializing game

java.lang.ArrayIndexOutOfBoundsException: 256
	at jajo_11.ShadowWorld.ShadowWorld.getFreeBiomeId(ShadowWorld.java:1989)
	at jajo_11.ShadowWorld.ShadowWorld.postInit(ShadowWorld.java:1942)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)

I am out of biome IDs

**Comment by fewizz** [comment]
You setted Biome id > 256 in configs. Use ID < than 256.

**Comment by DPxKnightxZero** [comment]
The mod automatically detects open slots here are the slots used.
::Biome IDs::
DivineRPG - 255, 248
Aether - 247
Biomes O Plenty - 246, 163
Highlands - 162, 119
Runic Dungeon - 118
Soul Forest - 117, 108
Abyssal Craft - 107, 96
Atum - 95
Dimensional Doors - 94, 93
Elysium - 92, 84
Erebus - 83, 76
Extreme Biomes XL - 75, 48
Shadow world - 47 5, X
Thaumcraft - 46, 43
Twilight forest - 42, 24

**Comment by fewizz** [comment]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2387300-say-no-to-id-conflicts-install-anti-id-conflict

**Comment by DPxKnightxZero** [comment]
I will try it.

**Comment by DPxKnightxZero** [comment]
This was what the log gave me XD 

Total amount of free biome ids: F:\Minecraft\Minecraft\.minecraft\[FC]-FeverFinity-v4.0\config\AntiIDConflict\biomes\avaibleIDs.txt
List of free biome ids:

**Comment by DPxKnightxZero** [comment]
Fewizz I am going to need these feature soon ... I have almost maxed out biomes. Is there a way you can impliment a prototype soon? I can give you cell so you can text me and let me know when you have a test version.

**Comment by Adaptivity** [comment]
Personally I want this feature too :) but there are not ETA for this and fewizz even not started on it yet. The main focus for now to fix tons of crashes with the current code changes. When fewizz probably start looking into it.

**Comment by DPxKnightxZero** [comment]
Oh? I never knew that; thank you! :) That will help me fix some of the stupid biomes added by Pokecube.

**Comment by DPxKnightxZero** [comment]
I actually hit my limit of available biomes ... anyway you could start this sometime this month?

**Comment by Adaptivity** [comment]
@DPxKnightxZero I talked to @fewizz and he is interested in implementing this. He has a lot of ideas for NEID as well as for other mods but has very little time and this is a problem. So, this still in deeps of our fantasy...

**Comment by fewizz** [comment]
https://drive.google.com/file/d/0B0GYhmakgvItMEt4T2NEOW1GSFE/view?usp=sharing . ONLY FOR TESTING AND BUGFINDINGS. Now you can change BoP biomes ID (in conf) from 0 to ~32000. Not comp. with old worlds(temporarily)

**Comment by fewizz** [comment]
Oh, and biomesID ext. enables in mods/config/NEID.txt file.

**Comment by Adaptivity** [comment]
Mods to support:
- [ ] Realistic Terrain Generation (Crash on startup if biome ids higher than 256)
- [ ] Enhanced Biomes (Crash on world creation, seems to be biome id check)

Supported Mods:
- Biomes O Plenty (Biome id check, support on NEID side)
- Extrabiomes XL (No support required, no biome id check)
- Thaumcraft (No support required, no biome id check)
- Highlands (No support required, no biome id check)

**Comment by DPxKnightxZero** [comment]
I will start testing immediately!

**Comment by DPxKnightxZero** [comment]
Shadow worlds still doesn't work
https://gist.github.com/DPxKnightxZero/871a746486e641f7bb71

Testing with Aethercraft next.

**Comment by Adaptivity** [comment]
Read OP:
*Any mod which adds own dimension and biomes to it. Because if you have ids higher 127 for these mods, their biomes then may spawn in overworld. These things are really derpy sometimes...*
Change ids in supported mods.

**Comment by DPxKnightxZero** [comment]
Eh hehehe ... sorry.

**Comment by Adaptivity** [comment]
Vanilla currently uses 39 *basic* biome ids. So, you have 88 ids for biomes which are spawns in non-vanilla dimensions. Some mods (like DivineRPG as I remember) allows you to set ids higher than 127 but derpy things may arise (or may not). And you have 32k ids for vanilla dimension(Overworld/Nether/End) biomes. Not sure if it possible to fix this issue, probably only Mojang can do this...

**Comment by DPxKnightxZero** [comment]
Biomes O Plenty crash when using biome ID's #IDS USED 256 - 339
https://gist.github.com/DPxKnightxZero/a23b9c6ede77c5ffeb4d

**Comment by Adaptivity** [comment]
You have NEID 1.4.0...

**Comment by fewizz** [comment]
@DPxKnightxZero , jest remove antiidconflict =P

**Comment by SvEgiiVEteR** [comment]
@fewizz 
вообщем. для этих двух модов
aether-1.7.10-1.5.2.jar
AoA-2.4.B.jar
мод InGameInfoXML-1.7.10-2.8.1.82-universal не правильно отображает айди биома и его название(при полёте в мирах этих модов быстро меняется название биома например форестери-название биома мода, туда сюда туда сюда)
по этому сложно сказать коректно работает или нет в F3 аналогично, название биома не совпадает...
могу предположить что это может вызвать проблемы с другими модами...так как и F3 тоже показывает не коректное имя
но огромное спасибо за расширение биомов,давно мы это ждали))

**Comment by Bogdan-G** [comment]
come on? so simply expanded? I was waiting for this for a long time! And what about the network packets when handling above 256 biomes? because in many places (forge, cauldron(code bukkit, code spigot, etc) hammered 256?

**Comment by fewizz** [comment]
Пакеты/чанклоадер/Регистратор биомов BoP/и ещё кое-что было изменено

**Comment by SvEgiiVEteR** [comment]
@fewizz можно сделать последнюю расширение на id биомов + DataWatcher?
у меня как раз модов много потестирую
у этих двух модов иметься конфликт на DataWatcher
AoA-2.4.B.jar
weaponmod-1.14.3.jar

**Comment by DPxKnightxZero** [comment]
Alright so this is "Running" but very errored. After a great deal of testing I think you may need to create a custom ID table sorting mod that completely ignores the hardcoded ID's the major issues are as follows. The Biome ID Table does not match the terrain and great example is the biome table will say desert but in actuality it was the Taiga. Another example was the deep ocean was the plains biome. Also during generation while the original had an issue that caused partial chunk loading.

**Comment by Bogdan-G** [comment]
@DPxKnightxZero already wrote about it, because it derives from the type of byte, but we have the type int.

**Comment by fewizz** [comment]
@SvEgiiVEteR эх, врядль 1.5 выйдет... :cry:  Но все же что-нить для тебя попробую сделать

**Comment by SvEgiiVEteR** [comment]
@fewizz а что случилось проблемы в коде или личные? DataWatcher расширенный тоже хорошо, хоть это есть)

**Comment by jredfox** [comment]
ids above 127 will cause dimensions to spawn their biomes in the overworld? how are you extending the ids this mod sounds like it breaks everything.  is it compatible with mods calling the .getbiomearraylist ? this is where I here biome id expansion mods seem to break.

**Comment by fewizz** [comment]
@jredfox ,
It's compatible with mods calling the chunk.getbiomearraylist().

**Comment by Bogdan-G** [comment]
опять какие то байки

**Comment by jredfox** [comment]
well get this mod working to the point that it can work with dimensions mods over 127. Vanilla and forge that have ids above 127 - 255 do not spawn in the overwrold this is a bug with your mod get it working.  make sure it doesn't break anything and then get back to me.  I hear the blocks is incompatible with certain mods how? how can there be an incompatibility for extending the blocks when that is a simple extension.

**Comment by Bogdan-G** [comment]
@jredfox >Vanilla and forge that have ids above 127 - 255 do not spawn in the overwrold this is a bug with your mod get it working. 

strange, id 128-255 normal spawn and works with\without NEID

**Comment by fewizz** [comment]
"The chunk isn't the only thing calling the getbiomearray list the chunk extends the function getbiomearraylist in biome gen base that's what you need to worry about as well." OC, it isn't only, and I know about that(ChunkProviders(of mods also), and other classes). It's compatible with ALL(mb not... =P ) other mods, but i must add compatability on my side for allowing to choose BID > than 255. And, i must convert short array to bytearray all time, when getBiomeArray called.(buuut, if bytearray will be changed somwhere, original short array won't change.<<< Main problem atm)(for info: in chunk adds new method, called "getShortBiomeArray", that returns original shortarray, "getBiomeArray" converts shortarray to bytearray(Or i can store and short, and byte array in chunk, but this also problematic)) And if i need for compotability with other mods, i must change "getBiomeArray" calls to "getShortBiomeArray".(And sometimes change genLayers :cry: )
@jredfox , write here, if you have better idea how to implement this.
 (Oh... my english so bad... sorry, if you understood nothing).

**Comment by jredfox** [comment]
the source of the getbiomearray is in biomegenbase.  from what I have seen and heard you can either use forge asm to replace getbiomearray at biomegenbase to your method or you can change what defines a chunk to all short arrays.  Then make sure the biome array in biome gen base is also short array with 32767 slots also.  There is some code in the server packet 21, anvil chunk loader, gen package, seems to be in chunk package and then when I fixed all of this using base class edits it still didn't work. Of course I used integer arrays but, only 32767  slots and had everything in ints.

**Comment by fewizz** [comment]
You about elix_x?) (P.S. My changes(not all, most): https://github.com/UserNumberOne/Nothing/commits/master )

**Comment by jredfox** [comment]
I do not work with him. I just know his mods and what he was working on.  So it's a race between you people and him to get the biomes working properly go.

**Comment by fewizz** [comment]
@jredfox lol, i helped him little. :smile:

**Comment by jredfox** [comment]
well he needs more help. he is stuck on the gen package being inconsistent with his definitions making biomes not working. if he gets help with that and fixes that up it should all be good.

**Comment by jredfox** [comment]
well he needs more help. he is stuck on the gen package being inconsistent with his definitions making biomes not working. if he gets help with that and fixes that up it should all be good. then he can finally release aic with ids extended and make a backport to 1.7.10 later and I can finally finish my modpack! :) ?

**Comment by ALPHANUMERIC1** [comment]
Is there a way to extend biome IDs in 1.12.2? I'm having some problems with that right now.

**Comment by fewizz** [comment]
[link](https://github.com/fewizz/NotEnoughIDs/issues/75#issuecomment-405429010)
