### ISSUE TITLE
Strange installation error

### ISSUE THREAD

**Issue by SkySem** [fewizz/NotEnoughIDs#81]
![image](https://user-images.githubusercontent.com/38987710/47809130-33720500-dd51-11e8-9a80-abeacc0345ac.png)
The installation was made both on the server and on the client, but for some reason, when I try to log in server, I get the following. What to do in this situation?
Version 1.7.10

**Comment by SkySem** [comment]
What specific information should I provide?

**Comment by SkySem** [comment]
Server:thermos 1.7.10
Client: forgeLiteloager 1.7.10 [forge: last vetsion for 1.7.10)

**Comment by fewizz** [comment]
logs/modslist(client/server)

**Comment by SkySem** [comment]
**https://pastebin.com/q84KCDvU -- Server Report**

**Comment by fewizz** [comment]
ExtendDataWatcher option is enabled? if no, ll that's termos/nevermine bug.

**Comment by SkySem** [comment]
![image](https://user-images.githubusercontent.com/38987710/47999546-fcff0600-e113-11e8-903f-8a0d0b54e22d.png)
when setting the option "ExtendDataWatcher" appeared progress. lets me join  to the server. but knocks him out after a couple of seconds with the following error:

**Comment by fewizz** [comment]
neid(1.7.10) is incompatible with thermos

**Comment by SkySem** [comment]
Does reinstalling to another type of server help?

**Comment by SkySem** [comment]
**Reinstalling the server platform, solved the problem. Thank you very much**
