### ISSUE TITLE
NEID Doesn't Work

### ISSUE THREAD

**Issue by WanSouPL** [fewizz/NotEnoughIDs#83]

**Comment by WanSouPL** [comment]
I accidently clicked enter, but it just doesn't work i tried it and it doesnt work im on 1.12.2 and im using the latest version

**Comment by WanSouPL** [comment]
btw i get this
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Plugin (NotEnoughIDs-1.5.4.3.jar)
  OTGCorePlugin (OTG-Core.jar)
  LoadingPlugin (replaymod-1.12.2-2.1.4.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 1/12/19 2:57 AM
Description: Initializing game

java.lang.RuntimeException: Invalid id 256 - maximum id range exceeded.
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:296)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:282)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:115)
	at twilightforest.biomes.RegistryBiomeEvent$BiomeRegistry.register(RegistryBiomeEvent.java:249)
	at twilightforest.biomes.RegistryBiomeEvent.onRegisterBiomes(RegistryBiomeEvent.java:225)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_143_RegistryBiomeEvent_onRegisterBiomes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:296)
	at net.minecraftforge.registries.ForgeRegistry.add(ForgeRegistry.java:282)
	at net.minecraftforge.registries.ForgeRegistry.register(ForgeRegistry.java:115)
	at twilightforest.biomes.RegistryBiomeEvent$BiomeRegistry.register(RegistryBiomeEvent.java:249)
	at twilightforest.biomes.RegistryBiomeEvent.onRegisterBiomes(RegistryBiomeEvent.java:225)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_143_RegistryBiomeEvent_onRegisterBiomes_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 746193664 bytes (711 MB) / 1476395008 bytes (1408 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 49 mods loaded, 49 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version                 | Source                                        | Signature                                |
	|:----- |:----------------------- |:----------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft               | 1.12.2                  | minecraft.jar                                 | None                                     |
	| UCH   | mcp                     | 9.42                    | minecraft.jar                                 | None                                     |
	| UCH   | FML                     | 8.0.99.99               | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                   | 14.23.5.2768            | forge-1.12.2-14.23.5.2768.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | otgcore                 | 1.12.2 - v7             | minecraft.jar                                 | None                                     |
	| UCH   | replaymod-compat        | 1.12.2-2.1.4            | replaymod-1.12.2-2.1.4.jar                    | None                                     |
	| UCH   | replaymod               | 1.12.2-2.1.4            | replaymod-1.12.2-2.1.4.jar                    | None                                     |
	| UCH   | replaymod-editor        | 1.12.2-2.1.4            | replaymod-1.12.2-2.1.4.jar                    | None                                     |
	| UCH   | replaymod-extras        | 1.12.2-2.1.4            | replaymod-1.12.2-2.1.4.jar                    | None                                     |
	| UCH   | replaymod-online        | 1.12.2-2.1.4            | replaymod-1.12.2-2.1.4.jar                    | None                                     |
	| UCH   | replaymod-recording     | 1.12.2-2.1.4            | replaymod-1.12.2-2.1.4.jar                    | None                                     |
	| UCH   | replaymod-render        | 1.12.2-2.1.4            | replaymod-1.12.2-2.1.4.jar                    | None                                     |
	| UCH   | replaymod-replay        | 1.12.2-2.1.4            | replaymod-1.12.2-2.1.4.jar                    | None                                     |
	| UCH   | replaymod-simplepathing | 1.12.2-2.1.4            | replaymod-1.12.2-2.1.4.jar                    | None                                     |
	| UCH   | jei                     | 4.13.1.225              | jei_1.12.2-4.13.1.225.jar                     | None                                     |
	| UCH   | abyssalcraft            | 1.9.4.14                | AbyssalCraft-1.12.2-1.9.4.14.jar              | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCH   | additionalstructures    | 2.0.0                   | Additional-Structures-Mod-1.12.2.jar          | None                                     |
	| UCH   | backpack                | 3.0.2                   | Backpacks-Mod-1.12.2.jar                      | None                                     |
	| UCH   | baubles                 | 1.5.2                   | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UCH   | openterraingenerator    | v6                      | OpenTerrainGenerator-1.12.2+-+v6.jar          | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| UCH   | biomebundle             | 5.1                     | Biome_Bundle-1.12.2.jar                       | None                                     |
	| UCH   | biomesoplenty           | 7.0.1.2361              | BiomesOPlenty-1.12.2-7.0.1.2361-universal.jar | None                                     |
	| UCH   | bullseye                | 3.0.6                   | Bullseye-1.12.jar                             | None                                     |
	| UCH   | carryon                 | 1.9.3                   | Carry-On-Mod-1.12.2.jar                       | None                                     |
	| UCH   | cloudboots              | 1.4.0                   | Cloud-Boots-1.12.2.jar                        | None                                     |
	| UCH   | dungeonmod              | 1.0                     | Crawler-1.12.2.jar                            | None                                     |
	| UCH   | uteamcore               | 2.2.4.94                | u_team_core-1.12.2-2.2.4.94.jar               | None                                     |
	| UCH   | drawbridge              | 1.0.0.4                 | Draw-Bridge-Mod-1.12.2.jar                    | None                                     |
	| UCH   | umm3185118519           | alpha 1.1.1 - MC 1.12.2 | Extended-Items-and-Ores-1.12.2.jar            | None                                     |
	| UCH   | ichunutil               | 7.1.4                   | iChunUtil-1.12.2-7.1.4.jar                    | None                                     |
	| UCH   | inventorypets           | 1.4.9.9b                | InventoryPets-1.12.jar                        | None                                     |
	| UCH   | levelup2                | ${version}              | LevelUp-1.12.jar                              | None                                     |
	| UCH   | lex                     | 1.0.8                   | LibEx-1.12.2-1.0.8.jar                        | None                                     |
	| UCH   | lsc                     | 0.6.1.2-alpha           | Loot-Slash-Conquer-1.12.2.jar                 | None                                     |
	| UCH   | lumberjack              | 1.0                     | Lumberjack-Mod-1.12.2.jar                     | None                                     |
	| UCH   | reborncore              | 3.13.0.400              | RebornCore-1.12.2-3.13.0.400-universal.jar    | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCH   | mainmenuscale           | 1.0                     | Main-Menu-Scale-Mod-1.12.2.jar                | None                                     |
	| UCH   | mclib                   | 1.0                     | mclib-1.0-1.12.2.jar                          | None                                     |
	| UCH   | metamorph               | 1.1.7                   | metamorph-1.1.7-1.12.2.jar                    | None                                     |
	| UCH   | cfm                     | 6.2.0                   | MrCrayfishs-Furniture-Mod-1.12.2.jar          | None                                     |
	| UCH   | nex                     | 2.0.8                   | NetherEx-Mod-1.12.2.jar                       | None                                     |
	| UCH   | neid                    | 1.5.4.3                 | NotEnoughIDs-1.5.4.3.jar                      | None                                     |
	| UCH   | nt                      | 1.0                     | Novam-Terram-1.12.2.jar                       | None                                     |
	| UCH   | repairgem               | 1.0.0                   | Repair-Gem-Mod-1.12.2.jar                     | None                                     |
	| UCH   | shurikenmod             | 1.0.0                   | Shuriken-1.12.2.jar                           | None                                     |
	| UCH   | simplisticsuperswords   | 1.5.0                   | Simplistic-Super-Swords-Mod-1.12.2.jar        | None                                     |
	| UCH   | smoothbedrock           | 1.12.2-3.0.0.102        | Smooth-Bedrock-Mod-1.12.2.jar                 | None                                     |
	| UCH   | torohealthmod           | 1.12.2-11               | ToroCrafts-Damage-Indicators-Mod-1.12.2.jar   | None                                     |
	| UCH   | twilightforest          | 3.7.424                 | Twilight-Forest-1.12.jar                      | None                                     |

	Loaded coremods (and transformers): 
Plugin (NotEnoughIDs-1.5.4.3.jar)
  ru.fewizz.neid.asm.Transformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
LoadingPlugin (replaymod-1.12.2-2.1.4.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 4400'
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.13.0.400
		Runtime Debofucsation 1
		RenderEngine: 1
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2768
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4835, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 6
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.3.0 - Build 20.19.15.4835
	OpenGlRenderer: Intel(R) HD Graphics 4400
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by fewizz** [comment]
use jeid for biome id ext.
