### ISSUE TITLE
Mod conflicts with ProtocolSupport

### ISSUE THREAD

**Issue by Zilacon** [fewizz/NotEnoughIDs#85]
This mod pretty much makes ProtocolSupport useless. As explained in the issue here: https://github.com/ProtocolSupport/ProtocolSupport/issues/1024

When you have this mod on your client you cannot render any of the blocks on the server that has protocol support.

Protocol Support allows you to connect to a latest 1.13.2 server using older protocols down to 1.4.7. Allowing bungeecord networks to simply have 1 HUB/Vanilla server instead of multiple for every minecraft version.

I am using this on my 1.7.10 Modpack.
Is there any way you could add support for this plugin?

**Comment by fewizz** [comment]
1.7.10 Isn't supported anymore. Sorry for that =(

**Comment by Zilacon** [comment]
Seriously? Why? It is the most used and developed for version of minecraft.
https://bot.notenoughmods.com/

Over 1200 mods made for 1.7.10 compared to a couple hundred for other versions.
This is a very serious issue, cant you make a one time patch to fix this?
@fewizz

**Comment by fewizz** [comment]
Ok, ill try ❤️

**Comment by Zilacon** [comment]
Thank you.

**Comment by fewizz** [comment]
works 🤔 
![image](https://user-images.githubusercontent.com/8060034/52732782-1268b380-2fd2-11e9-8421-d0fd3ad9c7fe.png)

**Comment by Zilacon** [comment]
With protocol support on a large modpack?
Ive tested it with and without NotEnoughItems it most certainly does not work.
It looks like this on the vanilla server:
![screenshot_45](https://user-images.githubusercontent.com/3002248/52747899-ca2d9f00-2f99-11e9-8c3b-96776330704f.png)

And like this on the modpack server:
![screenshot_33](https://user-images.githubusercontent.com/3002248/52747926-dade1500-2f99-11e9-9758-03890e8ce159.png)

**Comment by fewizz** [comment]
I used a modified protocolsupport plugin. [Here](https://1drv.ms/u/s!AiV461MeA-VWgSy-s955IiXeiG7p) it is, for testing

**Comment by Zilacon** [comment]
:O
![screenshot_50](https://user-images.githubusercontent.com/3002248/52790528-a743cf00-301b-11e9-9338-361f3b0e9805.png)

Holy shit it works! :D
Thank you so much, might i ask why the jar is so bulky now? went from 7MB to 25MB thats a pretty big jump.
And could you do a merge request to the ProtocolSupport github in hopes this will be supported in future versions?

**Comment by Zilacon** [comment]
It doesnt work on vanilla now tho :(
Is there no way to work for both vanilla and modded?
![screenshot_51](https://user-images.githubusercontent.com/3002248/52791917-ed4e6200-301e-11e9-801e-a5032f12764c.png)

**Comment by fewizz** [comment]
I can do that, but not today. =P

**Comment by Zilacon** [comment]
Awesome, let me know when you got another version to test :)

**Comment by fewizz** [comment]
https://drive.google.com/file/d/1GrAisxWCaqXo16nCe8RT_mV0HlRJvxH_/view?usp=sharing

**Comment by Zilacon** [comment]
Issue discussed & fixed on discord. Thank you <3!
