### ISSUE TITLE
DataWatcher - 1.7.10 - 1.5.0 alpha

### ISSUE THREAD

**Issue by ItzArty** [fewizz/NotEnoughIDs#91]
Hello, Im building modpack for version 1.7.10, Im using NEID v1.5.0 alpha, I did use this config:
`
neid {
    #  [default: false]
    B:CatchUnregisteredBlocks=false

    # Extend DataWatcher IDs. Vanilla limit is 31, new limit is 127. [default: false]
    B:ExtendDataWatcher=true

    # If true, only blocks with IDs > 4095 will disappear after removing NEID. [default: true]
    B:PostNeidWorldsSupport=true

    # Remove invalid (corrupted) blocks from the game. [default: false]
    B:RemoveInvalidBlocks=false
}
`

but my game still crashes due to that 31. Any helpful tips or solutions?

**Comment by Bogdan-G** [comment]
wut? log?

**Comment by fewizz** [comment]
1.5.0 alpha is not supported anymore.
