### ISSUE TITLE
Breaks Vertically Stacked Dimensions

### ISSUE THREAD

**Issue by NihilEntropy** [fewizz/NotEnoughIDs#92]
For some reason Vertically Stacked Dimensions Mod breaks when in the presence of this mod, in a very specific situation. The dimension loading by the floor portals cannot be initiated or interacted with when in survival mode. Weird...

**Comment by NihilEntropy** [comment]
I'll address this with Vertically Stacked Dimensions, as this happens with Just Enough IDs too.

**Comment by CD4017BE** [comment]
I found the cause of the problem:
[here](https://github.com/fewizz/NotEnoughIDs/blob/41fee843235b3b5fbf1c50d46818c891c0bb6632/src/main/java/ru/fewizz/neid/asm/group/block/TransformerGroupChunkPrimer.java#L53) the neid class transformer basically deletes the patch that [my class transformer](https://github.com/CD4017BE/VerticallyStackedDimensions/blob/96d1a03173924f39a088167e1493fd1e77cea98c/src/java/cd4017be/dimstack/asm/ChunkPrimerTransformer.java#L72-L87) did before.

**Comment by CD4017BE** [comment]
I'm currently trying to find out how to control the order in which class transformers are executed. So I could ensure that mine always runs after neid's.

**Comment by CD4017BE** [comment]
Got it fixed, this issue can be closed now!
