### ISSUE TITLE
Error: StackOverflowError:Unexpected error

### ISSUE THREAD

**Issue by Abril253** [fewizz/NotEnoughIDs#94]
Hello, being playing in 1.12.2 I have noticed that the game after being in my new world for a few hours ends up giving me the stackoverflow error.
Tracking between the mods which could give me the error I arrived at the result that "NotEnoughIDs" is responsible for the error.
Could someone help me correct the error please?

Error Code
https://paste.dimdev.org/ejidonukab.coffeescript
![Screenshot_1](https://user-images.githubusercontent.com/53060520/66257662-ae158280-e761-11e9-85dd-4590a7fd344e.png)

**Comment by fewizz** [comment]
No logs, link is invalid. Closing for now.
