### ISSUE TITLE
Crash game (1.12.2)

### ISSUE THREAD

**Issue by SeagalKru** [fewizz/NotEnoughIDs#98]
(Google translation from Russian)
Hey.
In my assembly I use a lot of mods that add a lot of biomes. Faced ID limit limitation. After installing your mod, I thought that the problem is solved. However, it still remains. Something is wrong? It is possible to help in solving this problem.
Game version 1.12.2.
Thank you!
PS: The crash file is attached.
[crash-2020-09-30_11.15.07-client.txt](https://github.com/fewizz/NotEnoughIDs/files/5304012/crash-2020-09-30_11.15.07-client.txt)

**Comment by fewizz** [comment]
[Пробуем](https://github.com/fewizz/NotEnoughIDs/issues/86#issuecomment-463642122)
